# Scraping

In [43]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
from urllib.parse import urljoin

In [44]:


url = "https://brilliantmaps.com/european-meat/"

response = requests.get(url)
print(response)

<Response [200]>

In [45]:
print(response.text)

<!DOCTYPE html>
<html lang="en-US" prefix="og: https://ogp.me/ns#">
<head >
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<script data-no-optimize="1" data-cfasync="false">!function(){"use strict";const t={adt_ei:{identityApiKey:"plainText",source:"url",type:"plaintext",priority:1},adt_eih:{identityApiKey:"sha256",source:"urlh",type:"hashed",priority:2},sh_kit:{identityApiKey:"sha256",source:"urlhck",type:"hashed",priority:3}},e=Object.keys(t);function i(t){return function(t){const e=t.match(/((?=([a-z0-9._!#$%+^&*()[\]<>-]+))\2@[a-z0-9._-]+\.[a-z0-9._-]+)/gi);return e?e[0]:""}(function(t){return t.replace(/\s/g,"")}(t.toLowerCase()))}!async function(){const n=new URL(window.location.href),o=n.searchParams;let a=null;const r=Object.entries(t).sort(([,t],[,e])=>t.priority-e.priority).map(([t])=>t);for(const e of r){const n=o.get(e),r=t[e];if(!n||!r)continue;const c=decodeURIComponent(n),d="plaintext"===r.type&&i(c),s="hashed"===r.type&&c;if(d||s){a={value:c,config:r};break}}if(a){const{value:t,config:e}=a;window.adthrive=window.adthrive||{},window.adthrive.cmd=window.adthrive.cmd||[],window.adthrive.cmd.push(function(){window.adthrive.identityApi({source:e.source,[e.identityApiKey]:t},({success:i,data:n})=>{i?window.adthrive.log("info","Plugin","detectEmails",`Identity API called with ${e.type} email: ${t}`,n):window.adthrive.log("warning","Plugin","detectEmails",`Failed to call Identity API with ${e.type} email: ${t}`,n)})})}!function(t,e){const i=new URL(e);t.forEach(t=>i.searchParams.delete(t)),history.replaceState(null,"",i.toString())}(e,n)}()}();
</script><style data-no-optimize="1" data-cfasync="false">
	.adthrive-ad {
		margin-top: 10px;
		margin-bottom: 10px;
		text-align: center;
		overflow-x: visible;
		clear: both;
		line-height: 0;
	}
	/* General mobile collapse player styles */
.adthrive-collapse-mobile-background {
    max-height:163px;
}
body:not(.adthrive-device-phone) .adthrive-player-position.adthrive-collapse-mobile.adthrive-collapse-top-center {
    top:auto!important;
    bottom:90px!important;
    left:0;
    transform:translateX(15%);
}

/* Tablet/Desktop Specific mobile collapse player styles */
body.adthrive-device-tablet .adthrive-collapse-mobile-background, body.adthrive-device-desktop .adthrive-collapse-mobile-background {
    display: none!important;
}
body.adthrive-device-tablet .adthrive-wrapper-float-close.adthrive-instream-close.adthrive-top-collapse-close svg > *,
body.adthrive-device-desktop .adthrive-wrapper-float-close.adthrive-instream-close.adthrive-top-collapse-close svg > * {
    stroke: black!important;
}

/* Desktop failsafe mobile collapse player styles */
body.device-adthrive-desktop .adthrive-player-position.adthrive-collapse-mobile.adthrive-collapse-top-center {
    left: auto;
    top: auto!important;
    transform: translateX(0%)!important;
}
body.device-adthrive-desktop .adthrive-player-position.adthrive-collapse-float.adthrive-collapse-bottom-right,
body.device-adthrive-desktop .adthrive-player-position.adthrive-collapse-mobile.adthrive-collapse-bottom-right{
    transform: translateX(0%)!important;
}</style>
<script data-no-optimize="1" data-cfasync="false">
	window.adthriveCLS = {
		enabledLocations: ['Content', 'Recipe'],
		injectedSlots: [],
		injectedFromPlugin: true,
		branch: '7b22443',bucket: 'prod',			};
	window.adthriveCLS.siteAds = {"betaTester":false,"targeting":[{"value":"61f161464ea5122710295937","key":"siteId"},{"value":"6233884d116d2e7088901ee9","key":"organizationId"},{"value":"Brilliant Maps","key":"siteName"},{"value":"AdThrive Edge","key":"service"},{"value":"on","key":"bidding"},{"value":["Science"],"key":"verticals"}],"siteUrl":"https://brilliantmaps.com/","siteId":"61f161464ea5122710295937","siteName":"Brilliant Maps","breakpoints":{"tablet":768,"desktop":1024},"cloudflare":null,"adUnits":[{"sequence":null,"targeting":[{"value":["Header"],"key":"location"}],"devices":["desktop","tablet"],"name":"Header","sticky":false,"location":"Header","dynamic":{"pageSelector":"body.single","spacing":0,"max":1,"lazyMax":null,"enable":true,"lazy":false,"elementSelector":".site-inner","skip":0,"classNames":[],"position":"beforebegin","every":1,"enabled":true},"stickyOverlapSelector":"","adSizes":[[728,90],[970,250],[970,90],[468,60],[320,50],[320,100],[1,1],[300,50],[728,250]],"priority":399,"autosize":true},{"sequence":null,"targeting":[{"value":["Content"],"key":"location"}],"devices":["desktop"],"name":"Content","sticky":false,"location":"Content","dynamic":{"pageSelector":"body.single","spacing":0.85,"max":3,"lazyMax":96,"enable":true,"lazy":true,"elementSelector":".entry-content > p","skip":4,"classNames":[],"position":"afterend","every":1,"enabled":true},"stickyOverlapSelector":"","adSizes":[[728,90],[336,280],[320,50],[468,60],[970,90],[250,250],[1,1],[320,100],[970,250],[1,2],[300,50],[300,300],[552,334],[728,250],[300,250]],"priority":199,"autosize":true},{"sequence":null,"targeting":[{"value":["Content"],"key":"location"}],"devices":["tablet","phone"],"name":"Content","sticky":false,"location":"Content","dynamic":{"pageSelector":"body.single","spacing":0.85,"max":3,"lazyMax":96,"enable":true,"lazy":true,"elementSelector":".entry-content > p","skip":4,"classNames":[],"position":"afterend","every":1,"enabled":true},"stickyOverlapSelector":"","adSizes":[[728,90],[336,280],[320,50],[468,60],[970,90],[250,250],[1,1],[320,100],[970,250],[1,2],[300,50],[300,300],[552,334],[728,250],[300,250]],"priority":199,"autosize":true},{"sequence":null,"targeting":[{"value":["Below Post"],"key":"location"}],"devices":["desktop","tablet","phone"],"name":"Below_Post","sticky":false,"location":"Below Post","dynamic":{"pageSelector":"body.single","spacing":0.7,"max":0,"lazyMax":10,"enable":true,"lazy":true,"elementSelector":".comment-list > li, .comment-respond","skip":0,"classNames":[],"position":"afterend","every":1,"enabled":true},"stickyOverlapSelector":"","adSizes":[[728,90],[336,280],[320,50],[468,60],[250,250],[1,1],[320,100],[300,250],[970,250],[728,250]],"priority":99,"autosize":true},{"sequence":null,"targeting":[{"value":["Footer"],"key":"location"},{"value":true,"key":"sticky"}],"devices":["desktop","tablet","phone"],"name":"Footer","sticky":true,"location":"Footer","dynamic":{"pageSelector":"","spacing":0,"max":1,"lazyMax":null,"enable":true,"lazy":false,"elementSelector":"body","skip":0,"classNames":[],"position":"beforeend","every":1,"enabled":true},"stickyOverlapSelector":"","adSizes":[[320,50],[320,100],[728,90],[970,90],[468,60],[1,1],[300,50]],"priority":-1,"autosize":true}],"adDensityLayout":{"mobile":{"adDensity":0.24,"onePerViewport":false},"pageOverrides":[],"desktop":{"adDensity":0.2,"onePerViewport":false}},"adDensityEnabled":true,"siteExperiments":[],"adTypes":{"sponsorTileDesktop":true,"interscrollerDesktop":true,"nativeBelowPostDesktop":true,"miniscroller":true,"largeFormatsMobile":true,"nativeMobileContent":true,"inRecipeRecommendationMobile":true,"nativeMobileRecipe":true,"sponsorTileMobile":true,"expandableCatalogAdsMobile":true,"frameAdsMobile":true,"outstreamMobile":true,"nativeHeaderMobile":true,"frameAdsDesktop":true,"inRecipeRecommendationDesktop":true,"expandableFooterDesktop":true,"nativeDesktopContent":true,"outstreamDesktop":true,"animatedFooter":true,"skylineHeader":false,"expandableFooter":true,"nativeDesktopSidebar":true,"videoFootersMobile":true,"videoFootersDesktop":true,"interscroller":true,"nativeDesktopRecipe":true,"nativeHeaderDesktop":true,"nativeBelowPostMobile":true,"expandableCatalogAdsDesktop":true,"largeFormatsDesktop":true},"adOptions":{"theTradeDesk":true,"thirdPartyCmp":{"enabled":false,"vendor":null,"injectPrivacyPreferencesLink":false},"undertone":false,"sidebarConfig":{"dynamicStickySidebar":{"minHeight":1800,"enabled":true,"blockedSelectors":[]}},"footerCloseButton":false,"teads":true,"seedtag":true,"pmp":true,"sharethrough":true,"optimizeVideoPlayersForEarnings":true,"removeVideoTitleWrapper":true,"pubMatic":true,"contentTermsFooterEnabled":true,"chicory":false,"infiniteScroll":false,"longerVideoAdPod":true,"yahoossp":true,"spa":false,"stickyContainerConfig":{"recipeDesktop":{"minHeight":null,"enabled":false},"blockedSelectors":[],"stickyHeaderSelectors":[],"content":{"minHeight":null,"enabled":false},"recipeMobile":{"minHeight":null,"enabled":false}},"gatedPrint":{"printClasses":[],"siteEmailServiceProviderId":null,"defaultOptIn":false,"closeButtonEnabled":false,"enabled":false,"newsletterPromptEnabled":false},"yieldmo":true,"californiaPrivacyPopup":{"privacyPolicyUrl":null,"enabled":false,"termsOfServiceUrl":null},"footerSelector":"","amazonUAM":true,"gamMCMEnabled":true,"gamMCMChildNetworkCode":"22678903639","stickyContainerAds":true,"rubicon":true,"restartStickyVideoPlayersAfterClose":true,"conversant":false,"openx":true,"customCreativeEnabled":true,"mobileHeaderHeight":1,"secColor":"#000000","unruly":true,"bRealTime":true,"adInViewTime":null,"gumgum":true,"comscoreFooter":false,"desktopInterstitial":false,"amx":true,"footerCloseButtonDesktop":true,"ozone":true,"isAutoOptimized":true,"trustx":true,"comscoreTAL":true,"bgColor":"#FFFFFF","advancePlaylistOptions":{"playlistPlayer":{"enabled":true},"relatedPlayer":{"enabled":true,"applyToFirst":true}},"kargo":true,"liveRampATS":true,"footerCloseButtonMobile":true,"interstitialBlockedPageSelectors":"","prioritizeShorterVideoAds":true,"allowSmallerAdSizes":true,"comscore":"General","blis":true,"wakeLock":{"desktopEnabled":true,"mobileValue":15,"mobileEnabled":true,"desktopValue":30},"mobileInterstitial":true,"tripleLift":true,"sensitiveCategories":["alc","ast","cosm","dat","gamc","pol","rel","wtl"],"liveRamp":true,"adthriveEmailIdentity":true,"criteo":true,"nativo":true,"infiniteScrollOptions":{"selector":"","heightThreshold":0},"siteAttributes":{"mobileHeaderSelectors":[],"desktopHeaderSelectors":[]},"dynamicContentSlotLazyLoading":true,"clsOptimizedAds":true,"ogury":true,"verticals":["Science"],"inImage":false,"stackadapt":true,"usCMP":{"enabled":false,"regions":[]},"advancePlaylist":true,"medianet":true,"acAlwaysSticky":false,"delayLoading":false,"inImageZone":null,"appNexus":true,"rise":true,"liveRampId":"","infiniteScrollRefresh":false,"indexExchange":true},"siteAdsProfiles":[],"thirdPartySiteConfig":{"partners":{"discounts":[]}},"featureRollouts":{"disable-kargo-spotlight":{"featureRolloutId":45,"data":{},"enabled":false}},"organizationData":{"organizationId":"6233884d116d2e7088901ee9","multiSiteOrg":false},"videoPlayers":{"contextual":{"autoplayCollapsibleEnabled":false,"overrideEmbedLocation":false,"defaultPlayerType":"static"},"videoEmbed":"wordpress","footerSelector":"","contentSpecificPlaylists":[],"players":[{"playlistId":"5loHUMkb","pageSelector":"body.single","devices":["desktop"],"description":"","skip":2,"title":"My Latest Videos","type":"stickyPlaylist","enabled":true,"elementSelector":".entry-content > p","id":4077458,"position":"afterend","saveVideoCloseState":false,"shuffle":false,"mobileHeaderSelector":null,"playerId":"Oegq2rPK","isCompleted":false},{"playlistId":"5loHUMkb","pageSelector":"body.single","devices":["mobile"],"mobileLocation":"top-center","description":"","skip":2,"title":"","type":"stickyPlaylist","enabled":true,"elementSelector":".entry-content > p","id":4078255,"position":"afterend","saveVideoCloseState":false,"shuffle":false,"mobileHeaderSelector":null,"playerId":"Oegq2rPK"},{"playlistId":"","pageSelector":"","devices":["mobile","desktop"],"mobileLocation":null,"description":"","skip":0,"title":"","type":"stationaryRelated","enabled":true,"elementSelector":"","id":4077457,"position":"","saveVideoCloseState":false,"shuffle":false,"playerId":"GzMW8SLK","isCompleted":true}],"partners":{"theTradeDesk":true,"unruly":true,"undertone":false,"gumgum":true,"seedtag":true,"amx":true,"ozone":true,"trustx":true,"pmp":true,"kargo":true,"stickyOutstream":{"desktop":{"enabled":true},"blockedPageSelectors":"","mobileLocation":"bottom-left","thirdPartyGamAdUnitName":null,"allowOnHomepage":true,"mobile":{"enabled":true},"saveVideoCloseState":false,"mobileHeaderSelector":"","allowForPageWithStickyPlayer":{"enabled":true}},"sharethrough":true,"blis":true,"tripleLift":true,"pubMatic":true,"criteo":true,"yahoossp":true,"nativo":true,"stackadapt":true,"yieldmo":true,"amazonUAM":true,"medianet":true,"rubicon":true,"appNexus":true,"rise":true,"openx":true,"indexExchange":true}}};</script>

<script data-no-optimize="1" data-cfasync="false">
(function(w, d) {
	w.adthrive = w.adthrive || {};
	w.adthrive.cmd = w.adthrive.cmd || [];
	w.adthrive.plugin = 'adthrive-ads-3.13.0';
	w.adthrive.host = 'ads.adthrive.com';
	w.adthrive.integration = 'plugin';

	var commitParam = (w.adthriveCLS && w.adthriveCLS.bucket !== 'prod' && w.adthriveCLS.branch) ? '&commit=' + w.adthriveCLS.branch : '';

	var s = d.createElement('script');
	s.async = true;
	s.referrerpolicy='no-referrer-when-downgrade';
	s.src = 'https://' + w.adthrive.host + '/sites/61f161464ea5122710295937/ads.min.js?referrer=' + w.encodeURIComponent(w.location.href) + commitParam + '&cb=' + (Math.floor(Math.random() * 100) + 1) + '';
	var n = d.getElementsByTagName('script')[0];
	n.parentNode.insertBefore(s, n);
})(window, document);
</script>
<link rel="dns-prefetch" href="https://ads.adthrive.com/"><link rel="preconnect" href="https://ads.adthrive.com/"><link rel="preconnect" href="https://ads.adthrive.com/" crossorigin>
<!-- Search Engine Optimization by Rank Math - https://rankmath.com/ -->
<title>Most Consumed Type of Meat (Including Fish &amp; Seafood) By European Country - Brilliant Maps</title>
<meta name="description" content="The map above shows the most consumed type of meat, including fish and seafood, in each Europe country. You can find the full list below but here are the winners for each type:"/>
<meta name="robots" content="follow, index, max-snippet:-1, max-video-preview:-1, max-image-preview:large"/>
<link rel="canonical" href="https://brilliantmaps.com/european-meat/" />
<meta property="og:locale" content="en_US" />
<meta property="og:type" content="article" />
<meta property="og:title" content="Most Consumed Type of Meat (Including Fish &amp; Seafood) By European Country - Brilliant Maps" />
<meta property="og:description" content="The map above shows the most consumed type of meat, including fish and seafood, in each Europe country. You can find the full list below but here are the winners for each type:" />
<meta property="og:url" content="https://brilliantmaps.com/european-meat/" />
<meta property="og:site_name" content="Brilliant Maps" />
<meta property="article:publisher" content="https://www.facebook.com/brilliantmaps" />
<meta property="article:section" content="Europe" />
<meta property="og:updated_time" content="2026-01-13T15:11:14+00:00" />
<meta property="og:image" content="https://brilliantmaps.com/wp-content/uploads/europan-meat-consumption.jpg" />
<meta property="og:image:secure_url" content="https://brilliantmaps.com/wp-content/uploads/europan-meat-consumption.jpg" />
<meta property="og:image:width" content="1080" />
<meta property="og:image:height" content="1080" />
<meta property="og:image:alt" content="Most Consumed Type of Meat (Including Fish &#038; Seafood) By European Country" />
<meta property="og:image:type" content="image/jpeg" />
<meta property="article:published_time" content="2024-12-09T12:16:33+00:00" />
<meta property="article:modified_time" content="2026-01-13T15:11:14+00:00" />
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:title" content="Most Consumed Type of Meat (Including Fish &amp; Seafood) By European Country - Brilliant Maps" />
<meta name="twitter:description" content="The map above shows the most consumed type of meat, including fish and seafood, in each Europe country. You can find the full list below but here are the winners for each type:" />
<meta name="twitter:site" content="@BrilliantMaps" />
<meta name="twitter:creator" content="@BrilliantMaps" />
<meta name="twitter:image" content="https://brilliantmaps.com/wp-content/uploads/europan-meat-consumption.jpg" />
<meta name="twitter:label1" content="Written by" />
<meta name="twitter:data1" content="Brilliant Maps" />
<meta name="twitter:label2" content="Time to read" />
<meta name="twitter:data2" content="3 minutes" />
<script type="application/ld+json" class="rank-math-schema">{"@context":"https://schema.org","@graph":[{"@type":"Organization","@id":"https://brilliantmaps.com/#organization","name":"Brilliant Maps","url":"https://brilliantmaps.com","sameAs":["https://www.facebook.com/brilliantmaps","https://twitter.com/BrilliantMaps","https://www.pinterest.com/brilliantmaps/","https://www.youtube.com/@BrilliantMaps","https://www.linkedin.com/company/brilliantmaps"]},{"@type":"WebSite","@id":"https://brilliantmaps.com/#website","url":"https://brilliantmaps.com","name":"Brilliant Maps","publisher":{"@id":"https://brilliantmaps.com/#organization"},"inLanguage":"en-US"},{"@type":"ImageObject","@id":"https://brilliantmaps.com/wp-content/uploads/europan-meat-consumption.jpg","url":"https://brilliantmaps.com/wp-content/uploads/europan-meat-consumption.jpg","width":"1080","height":"1080","inLanguage":"en-US"},{"@type":"WebPage","@id":"https://brilliantmaps.com/european-meat/#webpage","url":"https://brilliantmaps.com/european-meat/","name":"Most Consumed Type of Meat (Including Fish &amp; Seafood) By European Country - Brilliant Maps","datePublished":"2024-12-09T12:16:33+00:00","dateModified":"2026-01-13T15:11:14+00:00","isPartOf":{"@id":"https://brilliantmaps.com/#website"},"primaryImageOfPage":{"@id":"https://brilliantmaps.com/wp-content/uploads/europan-meat-consumption.jpg"},"inLanguage":"en-US"},{"@type":"Person","@id":"https://brilliantmaps.com/author/admin/","name":"Brilliant Maps","url":"https://brilliantmaps.com/author/admin/","image":{"@type":"ImageObject","@id":"https://secure.gravatar.com/avatar/582ddaff0ead104fd8b11338c65f8571e33cd41f9a7e5946476d704fbf14b5a1?s=96&amp;d=mm&amp;r=pg","url":"https://secure.gravatar.com/avatar/582ddaff0ead104fd8b11338c65f8571e33cd41f9a7e5946476d704fbf14b5a1?s=96&amp;d=mm&amp;r=pg","caption":"Brilliant Maps","inLanguage":"en-US"},"worksFor":{"@id":"https://brilliantmaps.com/#organization"}},{"@type":"Article","headline":"Most Consumed Type of Meat (Including Fish &amp; Seafood) By European Country - Brilliant Maps","datePublished":"2024-12-09T12:16:33+00:00","dateModified":"2026-01-13T15:11:14+00:00","articleSection":"Europe","author":{"@id":"https://brilliantmaps.com/author/admin/","name":"Brilliant Maps"},"publisher":{"@id":"https://brilliantmaps.com/#organization"},"description":"The map above shows the most consumed type of meat, including fish and seafood, in each Europe country. You can find the full list below but here are the winners for each type:","name":"Most Consumed Type of Meat (Including Fish &amp; Seafood) By European Country - Brilliant Maps","@id":"https://brilliantmaps.com/european-meat/#richSnippet","isPartOf":{"@id":"https://brilliantmaps.com/european-meat/#webpage"},"image":{"@id":"https://brilliantmaps.com/wp-content/uploads/europan-meat-consumption.jpg"},"inLanguage":"en-US","mainEntityOfPage":{"@id":"https://brilliantmaps.com/european-meat/#webpage"}}]}</script>
<!-- /Rank Math WordPress SEO plugin -->

<link rel='dns-prefetch' href='//fonts.googleapis.com' />
<link rel="alternate" type="application/rss+xml" title="Brilliant Maps &raquo; Feed" href="https://brilliantmaps.com/feed/" />
<link rel="alternate" type="application/rss+xml" title="Brilliant Maps &raquo; Comments Feed" href="https://brilliantmaps.com/comments/feed/" />
<link rel="alternate" type="application/rss+xml" title="Brilliant Maps &raquo; Most Consumed Type of Meat (Including Fish &#038; Seafood) By European Country Comments Feed" href="https://brilliantmaps.com/european-meat/feed/" />

In [46]:
print(len(response.text))

206870

In [47]:
soup = BeautifulSoup(response.text, "html.parser")

print(soup.title)

<title>Most Consumed Type of Meat (Including Fish &amp; Seafood) By European Country - Brilliant Maps</title>

In [48]:
tables = soup.find_all("table")

print(tables)

[<table class="tablepress tablepress-id-239" id="tablepress-239">
<thead>
<tr class="row-1">
<th class="column-1">Country</th><th class="column-2">Fish And Seafood KG Per Capita Per Year</th><th class="column-3">Beef KG Per Capita Per Year</th><th class="column-4">Pork KG Per Capita Per Year</th><th class="column-5">Chicken KG Per Capita Per Year</th><th class="column-6">Goat and Lamb KG Per Capita Per Year</th><th class="column-7">Other Meat KG Per Capita Per Year</th><th class="column-8">Total KG Per Capita Per Year</th>
</tr>
</thead>
<tbody class="row-striping row-hover">
<tr class="row-2">
<td class="column-1">Albania</td><td class="column-2">8.51</td><td class="column-3">15.19</td><td class="column-4">6.31</td><td class="column-5">22.56</td><td class="column-6">8.87</td><td class="column-7">0.27</td><td class="column-8">61.71</td>
</tr>
<tr class="row-3">
<td class="column-1">Armenia</td><td class="column-2">5.15</td><td class="column-3">25.76</td><td class="column-4">11.36</td><td class="column-5">18.45</td><td class="column-6">3.88</td><td class="column-7">0.04</td><td class="column-8">64.64</td>
</tr>
<tr class="row-4">
<td class="column-1"><a data-internallinksmanager029f6b8e52c="1257" href="https://brilliantmaps.com/country-maps/map-of-austria/" title="Map Of Austria The CIA No Longer Wants You To See">Austria</a></td><td class="column-2">14.43</td><td class="column-3">14.48</td><td class="column-4">42.82</td><td class="column-5">19.14</td><td class="column-6">1</td><td class="column-7">0.52</td><td class="column-8">92.39</td>
</tr>
<tr class="row-5">
<td class="column-1">Azerbaijan</td><td class="column-2">2.13</td><td class="column-3">15.03</td><td class="column-4">0.81</td><td class="column-5">16.06</td><td class="column-6">8.6</td><td class="column-7">0</td><td class="column-8">42.63</td>
</tr>
<tr class="row-6">
<td class="column-1">Belarus</td><td class="column-2">11.91</td><td class="column-3">22.63</td><td class="column-4">36.42</td><td class="column-5">35.13</td><td class="column-6">0.09</td><td class="column-7">0.19</td><td class="column-8">106.37</td>
</tr>
<tr class="row-7">
<td class="column-1">Belgium</td><td class="column-2">24.04</td><td class="column-3">12.93</td><td class="column-4">32.3</td><td class="column-5">16.25</td><td class="column-6">0.92</td><td class="column-7">2.08</td><td class="column-8">88.52</td>
</tr>
<tr class="row-8">
<td class="column-1"><a data-internallinksmanager029f6b8e52c="1020" href="https://brilliantmaps.com/country-maps/map-of-bosnia-and-herzegovina/" title="Map Of Bosnia and Herzegovina Created By The CIA">Bosnia and Herzegovina</a></td><td class="column-2">5.77</td><td class="column-3">13.27</td><td class="column-4">13.06</td><td class="column-5">21.82</td><td class="column-6">0.37</td><td class="column-7">0.4</td><td class="column-8">54.69</td>
</tr>
<tr class="row-9">
<td class="column-1">Bulgaria</td><td class="column-2">7.32</td><td class="column-3">3.61</td><td class="column-4">34.2</td><td class="column-5">20.87</td><td class="column-6">1.41</td><td class="column-7">0.75</td><td class="column-8">68.16</td>
</tr>
<tr class="row-10">
<td class="column-1">Croatia</td><td class="column-2">20.34</td><td class="column-3">14.46</td><td class="column-4">57.39</td><td class="column-5">19.54</td><td class="column-6">1.73</td><td class="column-7">1.05</td><td class="column-8">114.51</td>
</tr>
<tr class="row-11">
<td class="column-1">Cyprus</td><td class="column-2">19.3</td><td class="column-3">8.2</td><td class="column-4">34.4</td><td class="column-5">29.09</td><td class="column-6">4.14</td><td class="column-7">0.5</td><td class="column-8">95.63</td>
</tr>
<tr class="row-12">
<td class="column-1">Czech Republic</td><td class="column-2">10.68</td><td class="column-3">10.78</td><td class="column-4">47.28</td><td class="column-5">23.87</td><td class="column-6">0.29</td><td class="column-7">0.83</td><td class="column-8">93.73</td>
</tr>
<tr class="row-13">
<td class="column-1"><a data-internallinksmanager029f6b8e52c="884" href="https://brilliantmaps.com/country-maps/map-of-denmark/" title="Map Of Denmark Created By The CIA">Denmark</a></td><td class="column-2">22.81</td><td class="column-3">21.93</td><td class="column-4">25.74</td><td class="column-5">17.83</td><td class="column-6">0.72</td><td class="column-7">0.81</td><td class="column-8">89.84</td>
</tr>
<tr class="row-14">
<td class="column-1">Estonia</td><td class="column-2">13.1</td><td class="column-3">8.81</td><td class="column-4">38.06</td><td class="column-5">21.26</td><td class="column-6">0.4</td><td class="column-7">0.39</td><td class="column-8">82.02</td>
</tr>
<tr class="row-15">
<td class="column-1"><a data-internallinksmanager029f6b8e52c="1253" href="https://brilliantmaps.com/country-maps/map-of-finland/" title="Map Of Finland The CIA No Longer Wants You To See">Finland</a></td><td class="column-2">31.84</td><td class="column-3">17.34</td><td class="column-4">29.36</td><td class="column-5">23.67</td><td class="column-6">0.45</td><td class="column-7">0.8</td><td class="column-8">103.46</td>
</tr>
<tr class="row-16">
<td class="column-1"><a data-internallinksmanager029f6b8e52c="1248" href="https://brilliantmaps.com/country-maps/map-of-france/" title="Map Of France The CIA No Longer Wants You To See">France</a></td><td class="column-2">33.56</td><td class="column-3">23.22</td><td class="column-4">33.73</td><td class="column-5">24.6</td><td class="column-6">2.44</td><td class="column-7">0.61</td><td class="column-8">118.16</td>
</tr>
<tr class="row-17">
<td class="column-1"><a data-internallinksmanager029f6b8e52c="1238" href="https://brilliantmaps.com/us-maps/georgia-map/" title="Map of Georgia The Government Doesn’t Want You To See">Georgia</a></td><td class="column-2">10.51</td><td class="column-3">7.28</td><td class="column-4">12.3</td><td class="column-5">19.19</td><td class="column-6">1.34</td><td class="column-7">0.12</td><td class="column-8">50.74</td>
</tr>
<tr class="row-18">
<td class="column-1"><a data-internallinksmanager029f6b8e52c="1258" href="https://brilliantmaps.com/country-maps/map-of-germany/" title="Map Of Germany The CIA No Longer Wants You To See">Germany</a></td><td class="column-2">13.16</td><td class="column-3">14.05</td><td class="column-4">38.96</td><td class="column-5">16.51</td><td class="column-6">0.75</td><td class="column-7">1.04</td><td class="column-8">84.47</td>
</tr>
<tr class="row-19">
<td class="column-1"><a data-internallinksmanager029f6b8e52c="1015" href="https://brilliantmaps.com/country-maps/map-of-greece/" title="Map Of Greece Created By The CIA">Greece</a></td><td class="column-2">19.36</td><td class="column-3">14.8</td><td class="column-4">27.39</td><td class="column-5">26.23</td><td class="column-6">8.56</td><td class="column-7">1.94</td><td class="column-8">98.28</td>
</tr>
<tr class="row-20">
<td class="column-1">Hungary</td><td class="column-2">6.17</td><td class="column-3">5.4</td><td class="column-4">47.08</td><td class="column-5">23.69</td><td class="column-6">0.11</td><td class="column-7">0.36</td><td class="column-8">82.81</td>
</tr>
<tr class="row-21">
<td class="column-1">Iceland</td><td class="column-2">87.1</td><td class="column-3">16</td><td class="column-4">20.68</td><td class="column-5">30.74</td><td class="column-6">14.89</td><td class="column-7">11.12</td><td class="column-8">180.53</td>
</tr>
<tr class="row-22">
<td class="column-1">Ireland</td><td class="column-2">19.93</td><td class="column-3">23.63</td><td class="column-4">29.11</td><td class="column-5">31.18</td><td class="column-6">4.22</td><td class="column-7">2.53</td><td class="column-8">110.6</td>
</tr>
<tr class="row-23">
<td class="column-1"><a data-internallinksmanager029f6b8e52c="865" href="https://brilliantmaps.com/country-maps/map-of-italy/" title="Map Of Italy The CIA No Longer Wants You To See">Italy</a></td><td class="column-2">29.62</td><td class="column-3">16.22</td><td class="column-4">34.96</td><td class="column-5">20.31</td><td class="column-6">0.86</td><td class="column-7">1.22</td><td class="column-8">103.19</td>
</tr>
<tr class="row-24">
<td class="column-1"><a data-internallinksmanager029f6b8e52c="1018" href="https://brilliantmaps.com/country-maps/map-of-kazakhstan/" title="Map Of Kazakhstan Created By The CIA">Kazakhstan</a></td><td class="column-2">3.64</td><td class="column-3">24.83</td><td class="column-4">8.01</td><td class="column-5">21.82</td><td class="column-6">8.51</td><td class="column-7">7.02</td><td class="column-8">73.83</td>
</tr>
<tr class="row-25">
<td class="column-1">Latvia</td><td class="column-2">24.91</td><td class="column-3">5.68</td><td class="column-4">48.07</td><td class="column-5">29.29</td><td class="column-6">0.36</td><td class="column-7">0.26</td><td class="column-8">108.57</td>
</tr>
<tr class="row-26">
<td class="column-1">Lithuania</td><td class="column-2">29.59</td><td class="column-3">5.05</td><td class="column-4">48.86</td><td class="column-5">26.55</td><td class="column-6">0.38</td><td class="column-7">0.55</td><td class="column-8">110.98</td>
</tr>
<tr class="row-27">
<td class="column-1">Luxembourg</td><td class="column-2">31.11</td><td class="column-3">30.73</td><td class="column-4">33.17</td><td class="column-5">19.84</td><td class="column-6">1.09</td><td class="column-7">1.24</td><td class="column-8">117.18</td>
</tr>
<tr class="row-28">
<td class="column-1">Malta</td><td class="column-2">30.37</td><td class="column-3">17.72</td><td class="column-4">22.19</td><td class="column-5">24.01</td><td class="column-6">0.83</td><td class="column-7">0.65</td><td class="column-8">95.77</td>
</tr>
<tr class="row-29">
<td class="column-1">Moldova</td><td class="column-2">16.18</td><td class="column-3">1.12</td><td class="column-4">12.5</td><td class="column-5">24.93</td><td class="column-6">0.01</td><td class="column-7">0.28</td><td class="column-8">55.02</td>
</tr>
<tr class="row-30">
<td class="column-1"><a data-internallinksmanager029f6b8e52c="1022" href="https://brilliantmaps.com/country-maps/map-of-montenegro/" title="Map Of Montenegro Created By The CIA">Montenegro</a></td><td class="column-2">12.04</td><td class="column-3">14.01</td><td class="column-4">53.47</td><td class="column-5">19.22</td><td class="column-6">1.68</td><td class="column-7">0.05</td><td class="column-8">100.47</td>
</tr>
<tr class="row-31">
<td class="column-1"><a data-internallinksmanager029f6b8e52c="1251" href="https://brilliantmaps.com/country-maps/map-of-netherlands/" title="Map Of Netherlands The CIA No Longer Wants You To See">Netherlands</a></td><td class="column-2">19.66</td><td class="column-3">16.73</td><td class="column-4">31.09</td><td class="column-5">13.78</td><td class="column-6">0.97</td><td class="column-7">2.51</td><td class="column-8">84.74</td>
</tr>
<tr class="row-32">
<td class="column-1"><a data-internallinksmanager029f6b8e52c="1023" href="https://brilliantmaps.com/country-maps/map-of-north-macedonia/" title="Map Of North Macedonia Created By The CIA">North Macedonia</a></td><td class="column-2">7.01</td><td class="column-3">8.65</td><td class="column-4">14.48</td><td class="column-5">18.01</td><td class="column-6">0.8</td><td class="column-7">0.37</td><td class="column-8">49.32</td>
</tr>
<tr class="row-33">
<td class="column-1"><a data-internallinksmanager029f6b8e52c="896" href="https://brilliantmaps.com/country-maps/map-of-norway/" title="Map Of Norway The CIA No Longer Wants You To See">Norway</a></td><td class="column-2">49.87</td><td class="column-3">18.7</td><td class="column-4">25.79</td><td class="column-5">21.51</td><td class="column-6">4.52</td><td class="column-7">1.72</td><td class="column-8">122.11</td>
</tr>
<tr class="row-34">
<td class="column-1">Poland</td><td class="column-2">10.84</td><td class="column-3">0.25</td><td class="column-4">51.65</td><td class="column-5">29.53</td><td class="column-6">0.03</td><td class="column-7">0.15</td><td class="column-8">92.45</td>
</tr>
<tr class="row-35">
<td class="column-1"><a data-internallinksmanager029f6b8e52c="1016" href="https://brilliantmaps.com/country-maps/map-of-portugal/" title="Map Of Portugal Created By The CIA">Portugal</a></td><td class="column-2">54.33</td><td class="column-3">22.44</td><td class="column-4">40.24</td><td class="column-5">32.82</td><td class="column-6">2.29</td><td class="column-7">0.63</td><td class="column-8">152.75</td>
</tr>
<tr class="row-36">
<td class="column-1">Romania</td><td class="column-2">7.95</td><td class="column-3">4.56</td><td class="column-4">38.48</td><td class="column-5">21.59</td><td class="column-6">3.09</td><td class="column-7">0.17</td><td class="column-8">75.84</td>
</tr>
<tr class="row-37">
<td class="column-1"><a data-internallinksmanager029f6b8e52c="887" href="https://brilliantmaps.com/country-maps/map-of-russia/" title="Map Of Russia The CIA No Longer Wants You To See">Russia</a></td><td class="column-2">22.91</td><td class="column-3">12.51</td><td class="column-4">29.51</td><td class="column-5">34.23</td><td class="column-6">1.45</td><td class="column-7">4.01</td><td class="column-8">104.62</td>
</tr>
<tr class="row-38">
<td class="column-1">Serbia</td><td class="column-2">7.93</td><td class="column-3">9.82</td><td class="column-4">49.11</td><td class="column-5">11.46</td><td class="column-6">4.22</td><td class="column-7">0.03</td><td class="column-8">82.57</td>
</tr>
<tr class="row-39">
<td class="column-1"><a data-internallinksmanager029f6b8e52c="1025" href="https://brilliantmaps.com/country-maps/map-of-slovakia/" title="Map Of Slovakia Created By The CIA">Slovakia</a></td><td class="column-2">9.85</td><td class="column-3">6.79</td><td class="column-4">40.11</td><td class="column-5">12.38</td><td class="column-6">0.11</td><td class="column-7">1.22</td><td class="column-8">70.46</td>
</tr>
<tr class="row-40">
<td class="column-1"><a data-internallinksmanager029f6b8e52c="1024" href="https://brilliantmaps.com/country-maps/map-of-slovenia/" title="Map Of Slovenia Created By The CIA">Slovenia</a></td><td class="column-2">12.95</td><td class="column-3">12.2</td><td class="column-4">21.18</td><td class="column-5">25.91</td><td class="column-6">0.79</td><td class="column-7">0.35</td><td class="column-8">73.38</td>
</tr>
<tr class="row-41">
<td class="column-1"><a data-internallinksmanager029f6b8e52c="1017" href="https://brilliantmaps.com/country-maps/map-of-spain/" title="Map Of Spain Created By The CIA">Spain</a></td><td class="column-2">40.05</td><td class="column-3">12.92</td><td class="column-4">56.5</td><td class="column-5">32.1</td><td class="column-6">1.87</td><td class="column-7">1.36</td><td class="column-8">144.8</td>
</tr>
<tr class="row-42">
<td class="column-1"><a data-internallinksmanager029f6b8e52c="1254" href="https://brilliantmaps.com/country-maps/map-of-sweden/" title="Map Of Sweden The CIA No Longer Wants You To See">Sweden</a></td><td class="column-2">30.63</td><td class="column-3">22</td><td class="column-4">28.2</td><td class="column-5">16.35</td><td class="column-6">1.31</td><td class="column-7">0.21</td><td class="column-8">98.7</td>
</tr>
<tr class="row-43">
<td class="column-1"><a data-internallinksmanager029f6b8e52c="1252" href="https://brilliantmaps.com/country-maps/map-of-switzerland/" title="Map Of Switzerland The CIA No Longer Wants You To See">Switzerland</a></td><td class="column-2">16.71</td><td class="column-3">18.68</td><td class="column-4">27.7</td><td class="column-5">18.01</td><td class="column-6">1.27</td><td class="column-7">1.02</td><td class="column-8">83.39</td>
</tr>
<tr class="row-44">
<td class="column-1">Turkey</td><td class="column-2">5.44</td><td class="column-3">18.56</td><td class="column-4">0</td><td class="column-5">21.16</td><td class="column-6">7.04</td><td class="column-7">0.02</td><td class="column-8">52.22</td>
</tr>
<tr class="row-45">
<td class="column-1"><a data-internallinksmanager029f6b8e52c="1027" href="https://brilliantmaps.com/country-maps/map-of-ukraine/" title="Map Of Ukraine Created By The CIA">Ukraine</a></td><td class="column-2">16.02</td><td class="column-3">6.2</td><td class="column-4">18.25</td><td class="column-5">22.87</td><td class="column-6">0.27</td><td class="column-7">0.37</td><td class="column-8">63.98</td>
</tr>
<tr class="row-46">
<td class="column-1"><a data-internallinksmanager029f6b8e52c="897" href="https://brilliantmaps.com/country-maps/map-of-united-kingdom/" title="Map Of United Kingdom Created By The CIA">United Kingdom</a></td><td class="column-2">18.01</td><td class="column-3">17.3</td><td class="column-4">26.17</td><td class="column-5">35.5</td><td class="column-6">4.1</td><td class="column-7">1.01</td><td class="column-8">102.09</td>
</tr>
</tbody>
</table>]

In [49]:
print(len(tables))

1

In [50]:
tables

[<table class="tablepress tablepress-id-239" id="tablepress-239">
 <thead>
 <tr class="row-1">
 <th class="column-1">Country</th><th class="column-2">Fish And Seafood KG Per Capita Per Year</th><th class="column-3">Beef KG Per Capita Per Year</th><th class="column-4">Pork KG Per Capita Per Year</th><th class="column-5">Chicken KG Per Capita Per Year</th><th class="column-6">Goat and Lamb KG Per Capita Per Year</th><th class="column-7">Other Meat KG Per Capita Per Year</th><th class="column-8">Total KG Per Capita Per Year</th>
 </tr>
 </thead>
 <tbody class="row-striping row-hover">
 <tr class="row-2">
 <td class="column-1">Albania</td><td class="column-2">8.51</td><td class="column-3">15.19</td><td class="column-4">6.31</td><td class="column-5">22.56</td><td class="column-6">8.87</td><td class="column-7">0.27</td><td class="column-8">61.71</td>
 </tr>
 <tr class="row-3">
 <td class="column-1">Armenia</td><td class="column-2">5.15</td><td class="column-3">25.76</td><td class="column-4">11.36</td><td class="column-5">18.45</td><td class="column-6">3.88</td><td class="column-7">0.04</td><td class="column-8">64.64</td>
 </tr>
 <tr class="row-4">
 <td class="column-1"><a data-internallinksmanager029f6b8e52c="1257" href="https://brilliantmaps.com/country-maps/map-of-austria/" title="Map Of Austria The CIA No Longer Wants You To See">Austria</a></td><td class="column-2">14.43</td><td class="column-3">14.48</td><td class="column-4">42.82</td><td class="column-5">19.14</td><td class="column-6">1</td><td class="column-7">0.52</td><td class="column-8">92.39</td>
 </tr>
 <tr class="row-5">
 <td class="column-1">Azerbaijan</td><td class="column-2">2.13</td><td class="column-3">15.03</td><td class="column-4">0.81</td><td class="column-5">16.06</td><td class="column-6">8.6</td><td class="column-7">0</td><td class="column-8">42.63</td>
 </tr>
 <tr class="row-6">
 <td class="column-1">Belarus</td><td class="column-2">11.91</td><td class="column-3">22.63</td><td class="column-4">36.42</td><td class="column-5">35.13</td><td class="column-6">0.09</td><td class="column-7">0.19</td><td class="column-8">106.37</td>
 </tr>
 <tr class="row-7">
 <td class="column-1">Belgium</td><td class="column-2">24.04</td><td class="column-3">12.93</td><td class="column-4">32.3</td><td class="column-5">16.25</td><td class="column-6">0.92</td><td class="column-7">2.08</td><td class="column-8">88.52</td>
 </tr>
 <tr class="row-8">
 <td class="column-1"><a data-internallinksmanager029f6b8e52c="1020" href="https://brilliantmaps.com/country-maps/map-of-bosnia-and-herzegovina/" title="Map Of Bosnia and Herzegovina Created By The CIA">Bosnia and Herzegovina</a></td><td class="column-2">5.77</td><td class="column-3">13.27</td><td class="column-4">13.06</td><td class="column-5">21.82</td><td class="column-6">0.37</td><td class="column-7">0.4</td><td class="column-8">54.69</td>
 </tr>
 <tr class="row-9">
 <td class="column-1">Bulgaria</td><td class="column-2">7.32</td><td class="column-3">3.61</td><td class="column-4">34.2</td><td class="column-5">20.87</td><td class="column-6">1.41</td><td class="column-7">0.75</td><td class="column-8">68.16</td>
 </tr>
 <tr class="row-10">
 <td class="column-1">Croatia</td><td class="column-2">20.34</td><td class="column-3">14.46</td><td class="column-4">57.39</td><td class="column-5">19.54</td><td class="column-6">1.73</td><td class="column-7">1.05</td><td class="column-8">114.51</td>
 </tr>
 <tr class="row-11">
 <td class="column-1">Cyprus</td><td class="column-2">19.3</td><td class="column-3">8.2</td><td class="column-4">34.4</td><td class="column-5">29.09</td><td class="column-6">4.14</td><td class="column-7">0.5</td><td class="column-8">95.63</td>
 </tr>
 <tr class="row-12">
 <td class="column-1">Czech Republic</td><td class="column-2">10.68</td><td class="column-3">10.78</td><td class="column-4">47.28</td><td class="column-5">23.87</td><td class="column-6">0.29</td><td class="column-7">0.83</td><td class="column-8">93.73</td>
 </tr>
 <tr class="row-13">
 <td class="column-1"><a data-internallinksmanager029f6b8e52c="884" href="https://brilliantmaps.com/country-maps/map-of-denmark/" title="Map Of Denmark Created By The CIA">Denmark</a></td><td class="column-2">22.81</td><td class="column-3">21.93</td><td class="column-4">25.74</td><td class="column-5">17.83</td><td class="column-6">0.72</td><td class="column-7">0.81</td><td class="column-8">89.84</td>
 </tr>
 <tr class="row-14">
 <td class="column-1">Estonia</td><td class="column-2">13.1</td><td class="column-3">8.81</td><td class="column-4">38.06</td><td class="column-5">21.26</td><td class="column-6">0.4</td><td class="column-7">0.39</td><td class="column-8">82.02</td>
 </tr>
 <tr class="row-15">
 <td class="column-1"><a data-internallinksmanager029f6b8e52c="1253" href="https://brilliantmaps.com/country-maps/map-of-finland/" title="Map Of Finland The CIA No Longer Wants You To See">Finland</a></td><td class="column-2">31.84</td><td class="column-3">17.34</td><td class="column-4">29.36</td><td class="column-5">23.67</td><td class="column-6">0.45</td><td class="column-7">0.8</td><td class="column-8">103.46</td>
 </tr>
 <tr class="row-16">
 <td class="column-1"><a data-internallinksmanager029f6b8e52c="1248" href="https://brilliantmaps.com/country-maps/map-of-france/" title="Map Of France The CIA No Longer Wants You To See">France</a></td><td class="column-2">33.56</td><td class="column-3">23.22</td><td class="column-4">33.73</td><td class="column-5">24.6</td><td class="column-6">2.44</td><td class="column-7">0.61</td><td class="column-8">118.16</td>
 </tr>
 <tr class="row-17">
 <td class="column-1"><a data-internallinksmanager029f6b8e52c="1238" href="https://brilliantmaps.com/us-maps/georgia-map/" title="Map of Georgia The Government Doesn’t Want You To See">Georgia</a></td><td class="column-2">10.51</td><td class="column-3">7.28</td><td class="column-4">12.3</td><td class="column-5">19.19</td><td class="column-6">1.34</td><td class="column-7">0.12</td><td class="column-8">50.74</td>
 </tr>
 <tr class="row-18">
 <td class="column-1"><a data-internallinksmanager029f6b8e52c="1258" href="https://brilliantmaps.com/country-maps/map-of-germany/" title="Map Of Germany The CIA No Longer Wants You To See">Germany</a></td><td class="column-2">13.16</td><td class="column-3">14.05</td><td class="column-4">38.96</td><td class="column-5">16.51</td><td class="column-6">0.75</td><td class="column-7">1.04</td><td class="column-8">84.47</td>
 </tr>
 <tr class="row-19">
 <td class="column-1"><a data-internallinksmanager029f6b8e52c="1015" href="https://brilliantmaps.com/country-maps/map-of-greece/" title="Map Of Greece Created By The CIA">Greece</a></td><td class="column-2">19.36</td><td class="column-3">14.8</td><td class="column-4">27.39</td><td class="column-5">26.23</td><td class="column-6">8.56</td><td class="column-7">1.94</td><td class="column-8">98.28</td>
 </tr>
 <tr class="row-20">
 <td class="column-1">Hungary</td><td class="column-2">6.17</td><td class="column-3">5.4</td><td class="column-4">47.08</td><td class="column-5">23.69</td><td class="column-6">0.11</td><td class="column-7">0.36</td><td class="column-8">82.81</td>
 </tr>
 <tr class="row-21">
 <td class="column-1">Iceland</td><td class="column-2">87.1</td><td class="column-3">16</td><td class="column-4">20.68</td><td class="column-5">30.74</td><td class="column-6">14.89</td><td class="column-7">11.12</td><td class="column-8">180.53</td>
 </tr>
 <tr class="row-22">
 <td class="column-1">Ireland</td><td class="column-2">19.93</td><td class="column-3">23.63</td><td class="column-4">29.11</td><td class="column-5">31.18</td><td class="column-6">4.22</td><td class="column-7">2.53</td><td class="column-8">110.6</td>
 </tr>
 <tr class="row-23">
 <td class="column-1"><a data-internallinksmanager029f6b8e52c="865" href="https://brilliantmaps.com/country-maps/map-of-italy/" title="Map Of Italy The CIA No Longer Wants You To See">Italy</a></td><td class="column-2">29.62</td><td class="column-3">16.22</td><td class="column-4">34.96</td><td class="column-5">20.31</td><td class="column-6">0.86</td><td class="column-7">1.22</td><td class="column-8">103.19</td>
 </tr>
 <tr class="row-24">
 <td class="column-1"><a data-internallinksmanager029f6b8e52c="1018" href="https://brilliantmaps.com/country-maps/map-of-kazakhstan/" title="Map Of Kazakhstan Created By The CIA">Kazakhstan</a></td><td class="column-2">3.64</td><td class="column-3">24.83</td><td class="column-4">8.01</td><td class="column-5">21.82</td><td class="column-6">8.51</td><td class="column-7">7.02</td><td class="column-8">73.83</td>
 </tr>
 <tr class="row-25">
 <td class="column-1">Latvia</td><td class="column-2">24.91</td><td class="column-3">5.68</td><td class="column-4">48.07</td><td class="column-5">29.29</td><td class="column-6">0.36</td><td class="column-7">0.26</td><td class="column-8">108.57</td>
 </tr>
 <tr class="row-26">
 <td class="column-1">Lithuania</td><td class="column-2">29.59</td><td class="column-3">5.05</td><td class="column-4">48.86</td><td class="column-5">26.55</td><td class="column-6">0.38</td><td class="column-7">0.55</td><td class="column-8">110.98</td>
 </tr>
 <tr class="row-27">
 <td class="column-1">Luxembourg</td><td class="column-2">31.11</td><td class="column-3">30.73</td><td class="column-4">33.17</td><td class="column-5">19.84</td><td class="column-6">1.09</td><td class="column-7">1.24</td><td class="column-8">117.18</td>
 </tr>
 <tr class="row-28">
 <td class="column-1">Malta</td><td class="column-2">30.37</td><td class="column-3">17.72</td><td class="column-4">22.19</td><td class="column-5">24.01</td><td class="column-6">0.83</td><td class="column-7">0.65</td><td class="column-8">95.77</td>
 </tr>
 <tr class="row-29">
 <td class="column-1">Moldova</td><td class="column-2">16.18</td><td class="column-3">1.12</td><td class="column-4">12.5</td><td class="column-5">24.93</td><td class="column-6">0.01</td><td class="column-7">0.28</td><td class="column-8">55.02</td>
 </tr>
 <tr class="row-30">
 <td class="column-1"><a data-internallinksmanager029f6b8e52c="1022" href="https://brilliantmaps.com/country-maps/map-of-montenegro/" title="Map Of Montenegro Created By The CIA">Montenegro</a></td><td class="column-2">12.04</td><td class="column-3">14.01</td><td class="column-4">53.47</td><td class="column-5">19.22</td><td class="column-6">1.68</td><td class="column-7">0.05</td><td class="column-8">100.47</td>
 </tr>
 <tr class="row-31">
 <td class="column-1"><a data-internallinksmanager029f6b8e52c="1251" href="https://brilliantmaps.com/country-maps/map-of-netherlands/" title="Map Of Netherlands The CIA No Longer Wants You To See">Netherlands</a></td><td class="column-2">19.66</td><td class="column-3">16.73</td><td class="column-4">31.09</td><td class="column-5">13.78</td><td class="column-6">0.97</td><td class="column-7">2.51</td><td class="column-8">84.74</td>
 </tr>
 <tr class="row-32">
 <td class="column-1"><a data-internallinksmanager029f6b8e52c="1023" href="https://brilliantmaps.com/country-maps/map-of-north-macedonia/" title="Map Of North Macedonia Created By The CIA">North Macedonia</a></td><td class="column-2">7.01</td><td class="column-3">8.65</td><td class="column-4">14.48</td><td class="column-5">18.01</td><td class="column-6">0.8</td><td class="column-7">0.37</td><td class="column-8">49.32</td>
 </tr>
 <tr class="row-33">
 <td class="column-1"><a data-internallinksmanager029f6b8e52c="896" href="https://brilliantmaps.com/country-maps/map-of-norway/" title="Map Of Norway The CIA No Longer Wants You To See">Norway</a></td><td class="column-2">49.87</td><td class="column-3">18.7</td><td class="column-4">25.79</td><td class="column-5">21.51</td><td class="column-6">4.52</td><td class="column-7">1.72</td><td class="column-8">122.11</td>
 </tr>
 <tr class="row-34">
 <td class="column-1">Poland</td><td class="column-2">10.84</td><td class="column-3">0.25</td><td class="column-4">51.65</td><td class="column-5">29.53</td><td class="column-6">0.03</td><td class="column-7">0.15</td><td class="column-8">92.45</td>
 </tr>
 <tr class="row-35">
 <td class="column-1"><a data-internallinksmanager029f6b8e52c="1016" href="https://brilliantmaps.com/country-maps/map-of-portugal/" title="Map Of Portugal Created By The CIA">Portugal</a></td><td class="column-2">54.33</td><td class="column-3">22.44</td><td class="column-4">40.24</td><td class="column-5">32.82</td><td class="column-6">2.29</td><td class="column-7">0.63</td><td class="column-8">152.75</td>
 </tr>
 <tr class="row-36">
 <td class="column-1">Romania</td><td class="column-2">7.95</td><td class="column-3">4.56</td><td class="column-4">38.48</td><td class="column-5">21.59</td><td class="column-6">3.09</td><td class="column-7">0.17</td><td class="column-8">75.84</td>
 </tr>
 <tr class="row-37">
 <td class="column-1"><a data-internallinksmanager029f6b8e52c="887" href="https://brilliantmaps.com/country-maps/map-of-russia/" title="Map Of Russia The CIA No Longer Wants You To See">Russia</a></td><td class="column-2">22.91</td><td class="column-3">12.51</td><td class="column-4">29.51</td><td class="column-5">34.23</td><td class="column-6">1.45</td><td class="column-7">4.01</td><td class="column-8">104.62</td>
 </tr>
 <tr class="row-38">
 <td class="column-1">Serbia</td><td class="column-2">7.93</td><td class="column-3">9.82</td><td class="column-4">49.11</td><td class="column-5">11.46</td><td class="column-6">4.22</td><td class="column-7">0.03</td><td class="column-8">82.57</td>
 </tr>
 <tr class="row-39">
 <td class="column-1"><a data-internallinksmanager029f6b8e52c="1025" href="https://brilliantmaps.com/country-maps/map-of-slovakia/" title="Map Of Slovakia Created By The CIA">Slovakia</a></td><td class="column-2">9.85</td><td class="column-3">6.79</td><td class="column-4">40.11</td><td class="column-5">12.38</td><td class="column-6">0.11</td><td class="column-7">1.22</td><td class="column-8">70.46</td>
 </tr>
 <tr class="row-40">
 <td class="column-1"><a data-internallinksmanager029f6b8e52c="1024" href="https://brilliantmaps.com/country-maps/map-of-slovenia/" title="Map Of Slovenia Created By The CIA">Slovenia</a></td><td class="column-2">12.95</td><td class="column-3">12.2</td><td class="column-4">21.18</td><td class="column-5">25.91</td><td class="column-6">0.79</td><td class="column-7">0.35</td><td class="column-8">73.38</td>
 </tr>
 <tr class="row-41">
 <td class="column-1"><a data-internallinksmanager029f6b8e52c="1017" href="https://brilliantmaps.com/country-maps/map-of-spain/" title="Map Of Spain Created By The CIA">Spain</a></td><td class="column-2">40.05</td><td class="column-3">12.92</td><td class="column-4">56.5</td><td class="column-5">32.1</td><td class="column-6">1.87</td><td class="column-7">1.36</td><td class="column-8">144.8</td>
 </tr>
 <tr class="row-42">
 <td class="column-1"><a data-internallinksmanager029f6b8e52c="1254" href="https://brilliantmaps.com/country-maps/map-of-sweden/" title="Map Of Sweden The CIA No Longer Wants You To See">Sweden</a></td><td class="column-2">30.63</td><td class="column-3">22</td><td class="column-4">28.2</td><td class="column-5">16.35</td><td class="column-6">1.31</td><td class="column-7">0.21</td><td class="column-8">98.7</td>
 </tr>
 <tr class="row-43">
 <td class="column-1"><a data-internallinksmanager029f6b8e52c="1252" href="https://brilliantmaps.com/country-maps/map-of-switzerland/" title="Map Of Switzerland The CIA No Longer Wants You To See">Switzerland</a></td><td class="column-2">16.71</td><td class="column-3">18.68</td><td class="column-4">27.7</td><td class="column-5">18.01</td><td class="column-6">1.27</td><td class="column-7">1.02</td><td class="column-8">83.39</td>
 </tr>
 <tr class="row-44">
 <td class="column-1">Turkey</td><td class="column-2">5.44</td><td class="column-3">18.56</td><td class="column-4">0</td><td class="column-5">21.16</td><td class="column-6">7.04</td><td class="column-7">0.02</td><td class="column-8">52.22</td>
 </tr>
 <tr class="row-45">
 <td class="column-1"><a data-internallinksmanager029f6b8e52c="1027" href="https://brilliantmaps.com/country-maps/map-of-ukraine/" title="Map Of Ukraine Created By The CIA">Ukraine</a></td><td class="column-2">16.02</td><td class="column-3">6.2</td><td class="column-4">18.25</td><td class="column-5">22.87</td><td class="column-6">0.27</td><td class="column-7">0.37</td><td class="column-8">63.98</td>
 </tr>
 <tr class="row-46">
 <td class="column-1"><a data-internallinksmanager029f6b8e52c="897" href="https://brilliantmaps.com/country-maps/map-of-united-kingdom/" title="Map Of United Kingdom Created By The CIA">United Kingdom</a></td><td class="column-2">18.01</td><td class="column-3">17.3</td><td class="column-4">26.17</td><td class="column-5">35.5</td><td class="column-6">4.1</td><td class="column-7">1.01</td><td class="column-8">102.09</td>
 </tr>
 </tbody>
 </table>]

In [51]:
table = tables[0]

In [52]:
table

<table class="tablepress tablepress-id-239" id="tablepress-239">
<thead>
<tr class="row-1">
<th class="column-1">Country</th><th class="column-2">Fish And Seafood KG Per Capita Per Year</th><th class="column-3">Beef KG Per Capita Per Year</th><th class="column-4">Pork KG Per Capita Per Year</th><th class="column-5">Chicken KG Per Capita Per Year</th><th class="column-6">Goat and Lamb KG Per Capita Per Year</th><th class="column-7">Other Meat KG Per Capita Per Year</th><th class="column-8">Total KG Per Capita Per Year</th>
</tr>
</thead>
<tbody class="row-striping row-hover">
<tr class="row-2">
<td class="column-1">Albania</td><td class="column-2">8.51</td><td class="column-3">15.19</td><td class="column-4">6.31</td><td class="column-5">22.56</td><td class="column-6">8.87</td><td class="column-7">0.27</td><td class="column-8">61.71</td>
</tr>
<tr class="row-3">
<td class="column-1">Armenia</td><td class="column-2">5.15</td><td class="column-3">25.76</td><td class="column-4">11.36</td><td class="column-5">18.45</td><td class="column-6">3.88</td><td class="column-7">0.04</td><td class="column-8">64.64</td>
</tr>
<tr class="row-4">
<td class="column-1"><a data-internallinksmanager029f6b8e52c="1257" href="https://brilliantmaps.com/country-maps/map-of-austria/" title="Map Of Austria The CIA No Longer Wants You To See">Austria</a></td><td class="column-2">14.43</td><td class="column-3">14.48</td><td class="column-4">42.82</td><td class="column-5">19.14</td><td class="column-6">1</td><td class="column-7">0.52</td><td class="column-8">92.39</td>
</tr>
<tr class="row-5">
<td class="column-1">Azerbaijan</td><td class="column-2">2.13</td><td class="column-3">15.03</td><td class="column-4">0.81</td><td class="column-5">16.06</td><td class="column-6">8.6</td><td class="column-7">0</td><td class="column-8">42.63</td>
</tr>
<tr class="row-6">
<td class="column-1">Belarus</td><td class="column-2">11.91</td><td class="column-3">22.63</td><td class="column-4">36.42</td><td class="column-5">35.13</td><td class="column-6">0.09</td><td class="column-7">0.19</td><td class="column-8">106.37</td>
</tr>
<tr class="row-7">
<td class="column-1">Belgium</td><td class="column-2">24.04</td><td class="column-3">12.93</td><td class="column-4">32.3</td><td class="column-5">16.25</td><td class="column-6">0.92</td><td class="column-7">2.08</td><td class="column-8">88.52</td>
</tr>
<tr class="row-8">
<td class="column-1"><a data-internallinksmanager029f6b8e52c="1020" href="https://brilliantmaps.com/country-maps/map-of-bosnia-and-herzegovina/" title="Map Of Bosnia and Herzegovina Created By The CIA">Bosnia and Herzegovina</a></td><td class="column-2">5.77</td><td class="column-3">13.27</td><td class="column-4">13.06</td><td class="column-5">21.82</td><td class="column-6">0.37</td><td class="column-7">0.4</td><td class="column-8">54.69</td>
</tr>
<tr class="row-9">
<td class="column-1">Bulgaria</td><td class="column-2">7.32</td><td class="column-3">3.61</td><td class="column-4">34.2</td><td class="column-5">20.87</td><td class="column-6">1.41</td><td class="column-7">0.75</td><td class="column-8">68.16</td>
</tr>
<tr class="row-10">
<td class="column-1">Croatia</td><td class="column-2">20.34</td><td class="column-3">14.46</td><td class="column-4">57.39</td><td class="column-5">19.54</td><td class="column-6">1.73</td><td class="column-7">1.05</td><td class="column-8">114.51</td>
</tr>
<tr class="row-11">
<td class="column-1">Cyprus</td><td class="column-2">19.3</td><td class="column-3">8.2</td><td class="column-4">34.4</td><td class="column-5">29.09</td><td class="column-6">4.14</td><td class="column-7">0.5</td><td class="column-8">95.63</td>
</tr>
<tr class="row-12">
<td class="column-1">Czech Republic</td><td class="column-2">10.68</td><td class="column-3">10.78</td><td class="column-4">47.28</td><td class="column-5">23.87</td><td class="column-6">0.29</td><td class="column-7">0.83</td><td class="column-8">93.73</td>
</tr>
<tr class="row-13">
<td class="column-1"><a data-internallinksmanager029f6b8e52c="884" href="https://brilliantmaps.com/country-maps/map-of-denmark/" title="Map Of Denmark Created By The CIA">Denmark</a></td><td class="column-2">22.81</td><td class="column-3">21.93</td><td class="column-4">25.74</td><td class="column-5">17.83</td><td class="column-6">0.72</td><td class="column-7">0.81</td><td class="column-8">89.84</td>
</tr>
<tr class="row-14">
<td class="column-1">Estonia</td><td class="column-2">13.1</td><td class="column-3">8.81</td><td class="column-4">38.06</td><td class="column-5">21.26</td><td class="column-6">0.4</td><td class="column-7">0.39</td><td class="column-8">82.02</td>
</tr>
<tr class="row-15">
<td class="column-1"><a data-internallinksmanager029f6b8e52c="1253" href="https://brilliantmaps.com/country-maps/map-of-finland/" title="Map Of Finland The CIA No Longer Wants You To See">Finland</a></td><td class="column-2">31.84</td><td class="column-3">17.34</td><td class="column-4">29.36</td><td class="column-5">23.67</td><td class="column-6">0.45</td><td class="column-7">0.8</td><td class="column-8">103.46</td>
</tr>
<tr class="row-16">
<td class="column-1"><a data-internallinksmanager029f6b8e52c="1248" href="https://brilliantmaps.com/country-maps/map-of-france/" title="Map Of France The CIA No Longer Wants You To See">France</a></td><td class="column-2">33.56</td><td class="column-3">23.22</td><td class="column-4">33.73</td><td class="column-5">24.6</td><td class="column-6">2.44</td><td class="column-7">0.61</td><td class="column-8">118.16</td>
</tr>
<tr class="row-17">
<td class="column-1"><a data-internallinksmanager029f6b8e52c="1238" href="https://brilliantmaps.com/us-maps/georgia-map/" title="Map of Georgia The Government Doesn’t Want You To See">Georgia</a></td><td class="column-2">10.51</td><td class="column-3">7.28</td><td class="column-4">12.3</td><td class="column-5">19.19</td><td class="column-6">1.34</td><td class="column-7">0.12</td><td class="column-8">50.74</td>
</tr>
<tr class="row-18">
<td class="column-1"><a data-internallinksmanager029f6b8e52c="1258" href="https://brilliantmaps.com/country-maps/map-of-germany/" title="Map Of Germany The CIA No Longer Wants You To See">Germany</a></td><td class="column-2">13.16</td><td class="column-3">14.05</td><td class="column-4">38.96</td><td class="column-5">16.51</td><td class="column-6">0.75</td><td class="column-7">1.04</td><td class="column-8">84.47</td>
</tr>
<tr class="row-19">
<td class="column-1"><a data-internallinksmanager029f6b8e52c="1015" href="https://brilliantmaps.com/country-maps/map-of-greece/" title="Map Of Greece Created By The CIA">Greece</a></td><td class="column-2">19.36</td><td class="column-3">14.8</td><td class="column-4">27.39</td><td class="column-5">26.23</td><td class="column-6">8.56</td><td class="column-7">1.94</td><td class="column-8">98.28</td>
</tr>
<tr class="row-20">
<td class="column-1">Hungary</td><td class="column-2">6.17</td><td class="column-3">5.4</td><td class="column-4">47.08</td><td class="column-5">23.69</td><td class="column-6">0.11</td><td class="column-7">0.36</td><td class="column-8">82.81</td>
</tr>
<tr class="row-21">
<td class="column-1">Iceland</td><td class="column-2">87.1</td><td class="column-3">16</td><td class="column-4">20.68</td><td class="column-5">30.74</td><td class="column-6">14.89</td><td class="column-7">11.12</td><td class="column-8">180.53</td>
</tr>
<tr class="row-22">
<td class="column-1">Ireland</td><td class="column-2">19.93</td><td class="column-3">23.63</td><td class="column-4">29.11</td><td class="column-5">31.18</td><td class="column-6">4.22</td><td class="column-7">2.53</td><td class="column-8">110.6</td>
</tr>
<tr class="row-23">
<td class="column-1"><a data-internallinksmanager029f6b8e52c="865" href="https://brilliantmaps.com/country-maps/map-of-italy/" title="Map Of Italy The CIA No Longer Wants You To See">Italy</a></td><td class="column-2">29.62</td><td class="column-3">16.22</td><td class="column-4">34.96</td><td class="column-5">20.31</td><td class="column-6">0.86</td><td class="column-7">1.22</td><td class="column-8">103.19</td>
</tr>
<tr class="row-24">
<td class="column-1"><a data-internallinksmanager029f6b8e52c="1018" href="https://brilliantmaps.com/country-maps/map-of-kazakhstan/" title="Map Of Kazakhstan Created By The CIA">Kazakhstan</a></td><td class="column-2">3.64</td><td class="column-3">24.83</td><td class="column-4">8.01</td><td class="column-5">21.82</td><td class="column-6">8.51</td><td class="column-7">7.02</td><td class="column-8">73.83</td>
</tr>
<tr class="row-25">
<td class="column-1">Latvia</td><td class="column-2">24.91</td><td class="column-3">5.68</td><td class="column-4">48.07</td><td class="column-5">29.29</td><td class="column-6">0.36</td><td class="column-7">0.26</td><td class="column-8">108.57</td>
</tr>
<tr class="row-26">
<td class="column-1">Lithuania</td><td class="column-2">29.59</td><td class="column-3">5.05</td><td class="column-4">48.86</td><td class="column-5">26.55</td><td class="column-6">0.38</td><td class="column-7">0.55</td><td class="column-8">110.98</td>
</tr>
<tr class="row-27">
<td class="column-1">Luxembourg</td><td class="column-2">31.11</td><td class="column-3">30.73</td><td class="column-4">33.17</td><td class="column-5">19.84</td><td class="column-6">1.09</td><td class="column-7">1.24</td><td class="column-8">117.18</td>
</tr>
<tr class="row-28">
<td class="column-1">Malta</td><td class="column-2">30.37</td><td class="column-3">17.72</td><td class="column-4">22.19</td><td class="column-5">24.01</td><td class="column-6">0.83</td><td class="column-7">0.65</td><td class="column-8">95.77</td>
</tr>
<tr class="row-29">
<td class="column-1">Moldova</td><td class="column-2">16.18</td><td class="column-3">1.12</td><td class="column-4">12.5</td><td class="column-5">24.93</td><td class="column-6">0.01</td><td class="column-7">0.28</td><td class="column-8">55.02</td>
</tr>
<tr class="row-30">
<td class="column-1"><a data-internallinksmanager029f6b8e52c="1022" href="https://brilliantmaps.com/country-maps/map-of-montenegro/" title="Map Of Montenegro Created By The CIA">Montenegro</a></td><td class="column-2">12.04</td><td class="column-3">14.01</td><td class="column-4">53.47</td><td class="column-5">19.22</td><td class="column-6">1.68</td><td class="column-7">0.05</td><td class="column-8">100.47</td>
</tr>
<tr class="row-31">
<td class="column-1"><a data-internallinksmanager029f6b8e52c="1251" href="https://brilliantmaps.com/country-maps/map-of-netherlands/" title="Map Of Netherlands The CIA No Longer Wants You To See">Netherlands</a></td><td class="column-2">19.66</td><td class="column-3">16.73</td><td class="column-4">31.09</td><td class="column-5">13.78</td><td class="column-6">0.97</td><td class="column-7">2.51</td><td class="column-8">84.74</td>
</tr>
<tr class="row-32">
<td class="column-1"><a data-internallinksmanager029f6b8e52c="1023" href="https://brilliantmaps.com/country-maps/map-of-north-macedonia/" title="Map Of North Macedonia Created By The CIA">North Macedonia</a></td><td class="column-2">7.01</td><td class="column-3">8.65</td><td class="column-4">14.48</td><td class="column-5">18.01</td><td class="column-6">0.8</td><td class="column-7">0.37</td><td class="column-8">49.32</td>
</tr>
<tr class="row-33">
<td class="column-1"><a data-internallinksmanager029f6b8e52c="896" href="https://brilliantmaps.com/country-maps/map-of-norway/" title="Map Of Norway The CIA No Longer Wants You To See">Norway</a></td><td class="column-2">49.87</td><td class="column-3">18.7</td><td class="column-4">25.79</td><td class="column-5">21.51</td><td class="column-6">4.52</td><td class="column-7">1.72</td><td class="column-8">122.11</td>
</tr>
<tr class="row-34">
<td class="column-1">Poland</td><td class="column-2">10.84</td><td class="column-3">0.25</td><td class="column-4">51.65</td><td class="column-5">29.53</td><td class="column-6">0.03</td><td class="column-7">0.15</td><td class="column-8">92.45</td>
</tr>
<tr class="row-35">
<td class="column-1"><a data-internallinksmanager029f6b8e52c="1016" href="https://brilliantmaps.com/country-maps/map-of-portugal/" title="Map Of Portugal Created By The CIA">Portugal</a></td><td class="column-2">54.33</td><td class="column-3">22.44</td><td class="column-4">40.24</td><td class="column-5">32.82</td><td class="column-6">2.29</td><td class="column-7">0.63</td><td class="column-8">152.75</td>
</tr>
<tr class="row-36">
<td class="column-1">Romania</td><td class="column-2">7.95</td><td class="column-3">4.56</td><td class="column-4">38.48</td><td class="column-5">21.59</td><td class="column-6">3.09</td><td class="column-7">0.17</td><td class="column-8">75.84</td>
</tr>
<tr class="row-37">
<td class="column-1"><a data-internallinksmanager029f6b8e52c="887" href="https://brilliantmaps.com/country-maps/map-of-russia/" title="Map Of Russia The CIA No Longer Wants You To See">Russia</a></td><td class="column-2">22.91</td><td class="column-3">12.51</td><td class="column-4">29.51</td><td class="column-5">34.23</td><td class="column-6">1.45</td><td class="column-7">4.01</td><td class="column-8">104.62</td>
</tr>
<tr class="row-38">
<td class="column-1">Serbia</td><td class="column-2">7.93</td><td class="column-3">9.82</td><td class="column-4">49.11</td><td class="column-5">11.46</td><td class="column-6">4.22</td><td class="column-7">0.03</td><td class="column-8">82.57</td>
</tr>
<tr class="row-39">
<td class="column-1"><a data-internallinksmanager029f6b8e52c="1025" href="https://brilliantmaps.com/country-maps/map-of-slovakia/" title="Map Of Slovakia Created By The CIA">Slovakia</a></td><td class="column-2">9.85</td><td class="column-3">6.79</td><td class="column-4">40.11</td><td class="column-5">12.38</td><td class="column-6">0.11</td><td class="column-7">1.22</td><td class="column-8">70.46</td>
</tr>
<tr class="row-40">
<td class="column-1"><a data-internallinksmanager029f6b8e52c="1024" href="https://brilliantmaps.com/country-maps/map-of-slovenia/" title="Map Of Slovenia Created By The CIA">Slovenia</a></td><td class="column-2">12.95</td><td class="column-3">12.2</td><td class="column-4">21.18</td><td class="column-5">25.91</td><td class="column-6">0.79</td><td class="column-7">0.35</td><td class="column-8">73.38</td>
</tr>
<tr class="row-41">
<td class="column-1"><a data-internallinksmanager029f6b8e52c="1017" href="https://brilliantmaps.com/country-maps/map-of-spain/" title="Map Of Spain Created By The CIA">Spain</a></td><td class="column-2">40.05</td><td class="column-3">12.92</td><td class="column-4">56.5</td><td class="column-5">32.1</td><td class="column-6">1.87</td><td class="column-7">1.36</td><td class="column-8">144.8</td>
</tr>
<tr class="row-42">
<td class="column-1"><a data-internallinksmanager029f6b8e52c="1254" href="https://brilliantmaps.com/country-maps/map-of-sweden/" title="Map Of Sweden The CIA No Longer Wants You To See">Sweden</a></td><td class="column-2">30.63</td><td class="column-3">22</td><td class="column-4">28.2</td><td class="column-5">16.35</td><td class="column-6">1.31</td><td class="column-7">0.21</td><td class="column-8">98.7</td>
</tr>
<tr class="row-43">
<td class="column-1"><a data-internallinksmanager029f6b8e52c="1252" href="https://brilliantmaps.com/country-maps/map-of-switzerland/" title="Map Of Switzerland The CIA No Longer Wants You To See">Switzerland</a></td><td class="column-2">16.71</td><td class="column-3">18.68</td><td class="column-4">27.7</td><td class="column-5">18.01</td><td class="column-6">1.27</td><td class="column-7">1.02</td><td class="column-8">83.39</td>
</tr>
<tr class="row-44">
<td class="column-1">Turkey</td><td class="column-2">5.44</td><td class="column-3">18.56</td><td class="column-4">0</td><td class="column-5">21.16</td><td class="column-6">7.04</td><td class="column-7">0.02</td><td class="column-8">52.22</td>
</tr>
<tr class="row-45">
<td class="column-1"><a data-internallinksmanager029f6b8e52c="1027" href="https://brilliantmaps.com/country-maps/map-of-ukraine/" title="Map Of Ukraine Created By The CIA">Ukraine</a></td><td class="column-2">16.02</td><td class="column-3">6.2</td><td class="column-4">18.25</td><td class="column-5">22.87</td><td class="column-6">0.27</td><td class="column-7">0.37</td><td class="column-8">63.98</td>
</tr>
<tr class="row-46">
<td class="column-1"><a data-internallinksmanager029f6b8e52c="897" href="https://brilliantmaps.com/country-maps/map-of-united-kingdom/" title="Map Of United Kingdom Created By The CIA">United Kingdom</a></td><td class="column-2">18.01</td><td class="column-3">17.3</td><td class="column-4">26.17</td><td class="column-5">35.5</td><td class="column-6">4.1</td><td class="column-7">1.01</td><td class="column-8">102.09</td>
</tr>
</tbody>
</table>

In [53]:
rows = table.find_all("tr")

print(len(rows))

46

In [54]:
rows

[<tr class="row-1">
 <th class="column-1">Country</th><th class="column-2">Fish And Seafood KG Per Capita Per Year</th><th class="column-3">Beef KG Per Capita Per Year</th><th class="column-4">Pork KG Per Capita Per Year</th><th class="column-5">Chicken KG Per Capita Per Year</th><th class="column-6">Goat and Lamb KG Per Capita Per Year</th><th class="column-7">Other Meat KG Per Capita Per Year</th><th class="column-8">Total KG Per Capita Per Year</th>
 </tr>,
 <tr class="row-2">
 <td class="column-1">Albania</td><td class="column-2">8.51</td><td class="column-3">15.19</td><td class="column-4">6.31</td><td class="column-5">22.56</td><td class="column-6">8.87</td><td class="column-7">0.27</td><td class="column-8">61.71</td>
 </tr>,
 <tr class="row-3">
 <td class="column-1">Armenia</td><td class="column-2">5.15</td><td class="column-3">25.76</td><td class="column-4">11.36</td><td class="column-5">18.45</td><td class="column-6">3.88</td><td class="column-7">0.04</td><td class="column-8">64.64</td>
 </tr>,
 <tr class="row-4">
 <td class="column-1"><a data-internallinksmanager029f6b8e52c="1257" href="https://brilliantmaps.com/country-maps/map-of-austria/" title="Map Of Austria The CIA No Longer Wants You To See">Austria</a></td><td class="column-2">14.43</td><td class="column-3">14.48</td><td class="column-4">42.82</td><td class="column-5">19.14</td><td class="column-6">1</td><td class="column-7">0.52</td><td class="column-8">92.39</td>
 </tr>,
 <tr class="row-5">
 <td class="column-1">Azerbaijan</td><td class="column-2">2.13</td><td class="column-3">15.03</td><td class="column-4">0.81</td><td class="column-5">16.06</td><td class="column-6">8.6</td><td class="column-7">0</td><td class="column-8">42.63</td>
 </tr>,
 <tr class="row-6">
 <td class="column-1">Belarus</td><td class="column-2">11.91</td><td class="column-3">22.63</td><td class="column-4">36.42</td><td class="column-5">35.13</td><td class="column-6">0.09</td><td class="column-7">0.19</td><td class="column-8">106.37</td>
 </tr>,
 <tr class="row-7">
 <td class="column-1">Belgium</td><td class="column-2">24.04</td><td class="column-3">12.93</td><td class="column-4">32.3</td><td class="column-5">16.25</td><td class="column-6">0.92</td><td class="column-7">2.08</td><td class="column-8">88.52</td>
 </tr>,
 <tr class="row-8">
 <td class="column-1"><a data-internallinksmanager029f6b8e52c="1020" href="https://brilliantmaps.com/country-maps/map-of-bosnia-and-herzegovina/" title="Map Of Bosnia and Herzegovina Created By The CIA">Bosnia and Herzegovina</a></td><td class="column-2">5.77</td><td class="column-3">13.27</td><td class="column-4">13.06</td><td class="column-5">21.82</td><td class="column-6">0.37</td><td class="column-7">0.4</td><td class="column-8">54.69</td>
 </tr>,
 <tr class="row-9">
 <td class="column-1">Bulgaria</td><td class="column-2">7.32</td><td class="column-3">3.61</td><td class="column-4">34.2</td><td class="column-5">20.87</td><td class="column-6">1.41</td><td class="column-7">0.75</td><td class="column-8">68.16</td>
 </tr>,
 <tr class="row-10">
 <td class="column-1">Croatia</td><td class="column-2">20.34</td><td class="column-3">14.46</td><td class="column-4">57.39</td><td class="column-5">19.54</td><td class="column-6">1.73</td><td class="column-7">1.05</td><td class="column-8">114.51</td>
 </tr>,
 <tr class="row-11">
 <td class="column-1">Cyprus</td><td class="column-2">19.3</td><td class="column-3">8.2</td><td class="column-4">34.4</td><td class="column-5">29.09</td><td class="column-6">4.14</td><td class="column-7">0.5</td><td class="column-8">95.63</td>
 </tr>,
 <tr class="row-12">
 <td class="column-1">Czech Republic</td><td class="column-2">10.68</td><td class="column-3">10.78</td><td class="column-4">47.28</td><td class="column-5">23.87</td><td class="column-6">0.29</td><td class="column-7">0.83</td><td class="column-8">93.73</td>
 </tr>,
 <tr class="row-13">
 <td class="column-1"><a data-internallinksmanager029f6b8e52c="884" href="https://brilliantmaps.com/country-maps/map-of-denmark/" title="Map Of Denmark Created By The CIA">Denmark</a></td><td class="column-2">22.81</td><td class="column-3">21.93</td><td class="column-4">25.74</td><td class="column-5">17.83</td><td class="column-6">0.72</td><td class="column-7">0.81</td><td class="column-8">89.84</td>
 </tr>,
 <tr class="row-14">
 <td class="column-1">Estonia</td><td class="column-2">13.1</td><td class="column-3">8.81</td><td class="column-4">38.06</td><td class="column-5">21.26</td><td class="column-6">0.4</td><td class="column-7">0.39</td><td class="column-8">82.02</td>
 </tr>,
 <tr class="row-15">
 <td class="column-1"><a data-internallinksmanager029f6b8e52c="1253" href="https://brilliantmaps.com/country-maps/map-of-finland/" title="Map Of Finland The CIA No Longer Wants You To See">Finland</a></td><td class="column-2">31.84</td><td class="column-3">17.34</td><td class="column-4">29.36</td><td class="column-5">23.67</td><td class="column-6">0.45</td><td class="column-7">0.8</td><td class="column-8">103.46</td>
 </tr>,
 <tr class="row-16">
 <td class="column-1"><a data-internallinksmanager029f6b8e52c="1248" href="https://brilliantmaps.com/country-maps/map-of-france/" title="Map Of France The CIA No Longer Wants You To See">France</a></td><td class="column-2">33.56</td><td class="column-3">23.22</td><td class="column-4">33.73</td><td class="column-5">24.6</td><td class="column-6">2.44</td><td class="column-7">0.61</td><td class="column-8">118.16</td>
 </tr>,
 <tr class="row-17">
 <td class="column-1"><a data-internallinksmanager029f6b8e52c="1238" href="https://brilliantmaps.com/us-maps/georgia-map/" title="Map of Georgia The Government Doesn’t Want You To See">Georgia</a></td><td class="column-2">10.51</td><td class="column-3">7.28</td><td class="column-4">12.3</td><td class="column-5">19.19</td><td class="column-6">1.34</td><td class="column-7">0.12</td><td class="column-8">50.74</td>
 </tr>,
 <tr class="row-18">
 <td class="column-1"><a data-internallinksmanager029f6b8e52c="1258" href="https://brilliantmaps.com/country-maps/map-of-germany/" title="Map Of Germany The CIA No Longer Wants You To See">Germany</a></td><td class="column-2">13.16</td><td class="column-3">14.05</td><td class="column-4">38.96</td><td class="column-5">16.51</td><td class="column-6">0.75</td><td class="column-7">1.04</td><td class="column-8">84.47</td>
 </tr>,
 <tr class="row-19">
 <td class="column-1"><a data-internallinksmanager029f6b8e52c="1015" href="https://brilliantmaps.com/country-maps/map-of-greece/" title="Map Of Greece Created By The CIA">Greece</a></td><td class="column-2">19.36</td><td class="column-3">14.8</td><td class="column-4">27.39</td><td class="column-5">26.23</td><td class="column-6">8.56</td><td class="column-7">1.94</td><td class="column-8">98.28</td>
 </tr>,
 <tr class="row-20">
 <td class="column-1">Hungary</td><td class="column-2">6.17</td><td class="column-3">5.4</td><td class="column-4">47.08</td><td class="column-5">23.69</td><td class="column-6">0.11</td><td class="column-7">0.36</td><td class="column-8">82.81</td>
 </tr>,
 <tr class="row-21">
 <td class="column-1">Iceland</td><td class="column-2">87.1</td><td class="column-3">16</td><td class="column-4">20.68</td><td class="column-5">30.74</td><td class="column-6">14.89</td><td class="column-7">11.12</td><td class="column-8">180.53</td>
 </tr>,
 <tr class="row-22">
 <td class="column-1">Ireland</td><td class="column-2">19.93</td><td class="column-3">23.63</td><td class="column-4">29.11</td><td class="column-5">31.18</td><td class="column-6">4.22</td><td class="column-7">2.53</td><td class="column-8">110.6</td>
 </tr>,
 <tr class="row-23">
 <td class="column-1"><a data-internallinksmanager029f6b8e52c="865" href="https://brilliantmaps.com/country-maps/map-of-italy/" title="Map Of Italy The CIA No Longer Wants You To See">Italy</a></td><td class="column-2">29.62</td><td class="column-3">16.22</td><td class="column-4">34.96</td><td class="column-5">20.31</td><td class="column-6">0.86</td><td class="column-7">1.22</td><td class="column-8">103.19</td>
 </tr>,
 <tr class="row-24">
 <td class="column-1"><a data-internallinksmanager029f6b8e52c="1018" href="https://brilliantmaps.com/country-maps/map-of-kazakhstan/" title="Map Of Kazakhstan Created By The CIA">Kazakhstan</a></td><td class="column-2">3.64</td><td class="column-3">24.83</td><td class="column-4">8.01</td><td class="column-5">21.82</td><td class="column-6">8.51</td><td class="column-7">7.02</td><td class="column-8">73.83</td>
 </tr>,
 <tr class="row-25">
 <td class="column-1">Latvia</td><td class="column-2">24.91</td><td class="column-3">5.68</td><td class="column-4">48.07</td><td class="column-5">29.29</td><td class="column-6">0.36</td><td class="column-7">0.26</td><td class="column-8">108.57</td>
 </tr>,
 <tr class="row-26">
 <td class="column-1">Lithuania</td><td class="column-2">29.59</td><td class="column-3">5.05</td><td class="column-4">48.86</td><td class="column-5">26.55</td><td class="column-6">0.38</td><td class="column-7">0.55</td><td class="column-8">110.98</td>
 </tr>,
 <tr class="row-27">
 <td class="column-1">Luxembourg</td><td class="column-2">31.11</td><td class="column-3">30.73</td><td class="column-4">33.17</td><td class="column-5">19.84</td><td class="column-6">1.09</td><td class="column-7">1.24</td><td class="column-8">117.18</td>
 </tr>,
 <tr class="row-28">
 <td class="column-1">Malta</td><td class="column-2">30.37</td><td class="column-3">17.72</td><td class="column-4">22.19</td><td class="column-5">24.01</td><td class="column-6">0.83</td><td class="column-7">0.65</td><td class="column-8">95.77</td>
 </tr>,
 <tr class="row-29">
 <td class="column-1">Moldova</td><td class="column-2">16.18</td><td class="column-3">1.12</td><td class="column-4">12.5</td><td class="column-5">24.93</td><td class="column-6">0.01</td><td class="column-7">0.28</td><td class="column-8">55.02</td>
 </tr>,
 <tr class="row-30">
 <td class="column-1"><a data-internallinksmanager029f6b8e52c="1022" href="https://brilliantmaps.com/country-maps/map-of-montenegro/" title="Map Of Montenegro Created By The CIA">Montenegro</a></td><td class="column-2">12.04</td><td class="column-3">14.01</td><td class="column-4">53.47</td><td class="column-5">19.22</td><td class="column-6">1.68</td><td class="column-7">0.05</td><td class="column-8">100.47</td>
 </tr>,
 <tr class="row-31">
 <td class="column-1"><a data-internallinksmanager029f6b8e52c="1251" href="https://brilliantmaps.com/country-maps/map-of-netherlands/" title="Map Of Netherlands The CIA No Longer Wants You To See">Netherlands</a></td><td class="column-2">19.66</td><td class="column-3">16.73</td><td class="column-4">31.09</td><td class="column-5">13.78</td><td class="column-6">0.97</td><td class="column-7">2.51</td><td class="column-8">84.74</td>
 </tr>,
 <tr class="row-32">
 <td class="column-1"><a data-internallinksmanager029f6b8e52c="1023" href="https://brilliantmaps.com/country-maps/map-of-north-macedonia/" title="Map Of North Macedonia Created By The CIA">North Macedonia</a></td><td class="column-2">7.01</td><td class="column-3">8.65</td><td class="column-4">14.48</td><td class="column-5">18.01</td><td class="column-6">0.8</td><td class="column-7">0.37</td><td class="column-8">49.32</td>
 </tr>,
 <tr class="row-33">
 <td class="column-1"><a data-internallinksmanager029f6b8e52c="896" href="https://brilliantmaps.com/country-maps/map-of-norway/" title="Map Of Norway The CIA No Longer Wants You To See">Norway</a></td><td class="column-2">49.87</td><td class="column-3">18.7</td><td class="column-4">25.79</td><td class="column-5">21.51</td><td class="column-6">4.52</td><td class="column-7">1.72</td><td class="column-8">122.11</td>
 </tr>,
 <tr class="row-34">
 <td class="column-1">Poland</td><td class="column-2">10.84</td><td class="column-3">0.25</td><td class="column-4">51.65</td><td class="column-5">29.53</td><td class="column-6">0.03</td><td class="column-7">0.15</td><td class="column-8">92.45</td>
 </tr>,
 <tr class="row-35">
 <td class="column-1"><a data-internallinksmanager029f6b8e52c="1016" href="https://brilliantmaps.com/country-maps/map-of-portugal/" title="Map Of Portugal Created By The CIA">Portugal</a></td><td class="column-2">54.33</td><td class="column-3">22.44</td><td class="column-4">40.24</td><td class="column-5">32.82</td><td class="column-6">2.29</td><td class="column-7">0.63</td><td class="column-8">152.75</td>
 </tr>,
 <tr class="row-36">
 <td class="column-1">Romania</td><td class="column-2">7.95</td><td class="column-3">4.56</td><td class="column-4">38.48</td><td class="column-5">21.59</td><td class="column-6">3.09</td><td class="column-7">0.17</td><td class="column-8">75.84</td>
 </tr>,
 <tr class="row-37">
 <td class="column-1"><a data-internallinksmanager029f6b8e52c="887" href="https://brilliantmaps.com/country-maps/map-of-russia/" title="Map Of Russia The CIA No Longer Wants You To See">Russia</a></td><td class="column-2">22.91</td><td class="column-3">12.51</td><td class="column-4">29.51</td><td class="column-5">34.23</td><td class="column-6">1.45</td><td class="column-7">4.01</td><td class="column-8">104.62</td>
 </tr>,
 <tr class="row-38">
 <td class="column-1">Serbia</td><td class="column-2">7.93</td><td class="column-3">9.82</td><td class="column-4">49.11</td><td class="column-5">11.46</td><td class="column-6">4.22</td><td class="column-7">0.03</td><td class="column-8">82.57</td>
 </tr>,
 <tr class="row-39">
 <td class="column-1"><a data-internallinksmanager029f6b8e52c="1025" href="https://brilliantmaps.com/country-maps/map-of-slovakia/" title="Map Of Slovakia Created By The CIA">Slovakia</a></td><td class="column-2">9.85</td><td class="column-3">6.79</td><td class="column-4">40.11</td><td class="column-5">12.38</td><td class="column-6">0.11</td><td class="column-7">1.22</td><td class="column-8">70.46</td>
 </tr>,
 <tr class="row-40">
 <td class="column-1"><a data-internallinksmanager029f6b8e52c="1024" href="https://brilliantmaps.com/country-maps/map-of-slovenia/" title="Map Of Slovenia Created By The CIA">Slovenia</a></td><td class="column-2">12.95</td><td class="column-3">12.2</td><td class="column-4">21.18</td><td class="column-5">25.91</td><td class="column-6">0.79</td><td class="column-7">0.35</td><td class="column-8">73.38</td>
 </tr>,
 <tr class="row-41">
 <td class="column-1"><a data-internallinksmanager029f6b8e52c="1017" href="https://brilliantmaps.com/country-maps/map-of-spain/" title="Map Of Spain Created By The CIA">Spain</a></td><td class="column-2">40.05</td><td class="column-3">12.92</td><td class="column-4">56.5</td><td class="column-5">32.1</td><td class="column-6">1.87</td><td class="column-7">1.36</td><td class="column-8">144.8</td>
 </tr>,
 <tr class="row-42">
 <td class="column-1"><a data-internallinksmanager029f6b8e52c="1254" href="https://brilliantmaps.com/country-maps/map-of-sweden/" title="Map Of Sweden The CIA No Longer Wants You To See">Sweden</a></td><td class="column-2">30.63</td><td class="column-3">22</td><td class="column-4">28.2</td><td class="column-5">16.35</td><td class="column-6">1.31</td><td class="column-7">0.21</td><td class="column-8">98.7</td>
 </tr>,
 <tr class="row-43">
 <td class="column-1"><a data-internallinksmanager029f6b8e52c="1252" href="https://brilliantmaps.com/country-maps/map-of-switzerland/" title="Map Of Switzerland The CIA No Longer Wants You To See">Switzerland</a></td><td class="column-2">16.71</td><td class="column-3">18.68</td><td class="column-4">27.7</td><td class="column-5">18.01</td><td class="column-6">1.27</td><td class="column-7">1.02</td><td class="column-8">83.39</td>
 </tr>,
 <tr class="row-44">
 <td class="column-1">Turkey</td><td class="column-2">5.44</td><td class="column-3">18.56</td><td class="column-4">0</td><td class="column-5">21.16</td><td class="column-6">7.04</td><td class="column-7">0.02</td><td class="column-8">52.22</td>
 </tr>,
 <tr class="row-45">
 <td class="column-1"><a data-internallinksmanager029f6b8e52c="1027" href="https://brilliantmaps.com/country-maps/map-of-ukraine/" title="Map Of Ukraine Created By The CIA">Ukraine</a></td><td class="column-2">16.02</td><td class="column-3">6.2</td><td class="column-4">18.25</td><td class="column-5">22.87</td><td class="column-6">0.27</td><td class="column-7">0.37</td><td class="column-8">63.98</td>
 </tr>,
 <tr class="row-46">
 <td class="column-1"><a data-internallinksmanager029f6b8e52c="897" href="https://brilliantmaps.com/country-maps/map-of-united-kingdom/" title="Map Of United Kingdom Created By The CIA">United Kingdom</a></td><td class="column-2">18.01</td><td class="column-3">17.3</td><td class="column-4">26.17</td><td class="column-5">35.5</td><td class="column-6">4.1</td><td class="column-7">1.01</td><td class="column-8">102.09</td>
 </tr>]

In [55]:
rows[0]

<tr class="row-1">
<th class="column-1">Country</th><th class="column-2">Fish And Seafood KG Per Capita Per Year</th><th class="column-3">Beef KG Per Capita Per Year</th><th class="column-4">Pork KG Per Capita Per Year</th><th class="column-5">Chicken KG Per Capita Per Year</th><th class="column-6">Goat and Lamb KG Per Capita Per Year</th><th class="column-7">Other Meat KG Per Capita Per Year</th><th class="column-8">Total KG Per Capita Per Year</th>
</tr>

In [56]:
rows[1]

<tr class="row-2">
<td class="column-1">Albania</td><td class="column-2">8.51</td><td class="column-3">15.19</td><td class="column-4">6.31</td><td class="column-5">22.56</td><td class="column-6">8.87</td><td class="column-7">0.27</td><td class="column-8">61.71</td>
</tr>

In [57]:
cells = rows[1].find_all(["th", "td"])
print(len(cells))

row_values = [cell.get_text(strip=True) for cell in cells]
print(row_values)

8
['Albania', '8.51', '15.19', '6.31', '22.56', '8.87', '0.27', '61.71']

In [58]:
row_values = []
for cell in cells:
    row_values.append(cell.get_text(strip=True))

In [59]:
row_values

['Albania', '8.51', '15.19', '6.31', '22.56', '8.87', '0.27', '61.71']

In [60]:
header_cells = rows[0].find_all(["th", "td"])
columns = [cell.get_text(strip=True) for cell in header_cells]

In [61]:
columns

['Country',
 'Fish And Seafood KG Per Capita Per Year',
 'Beef KG Per Capita Per Year',
 'Pork KG Per Capita Per Year',
 'Chicken KG Per Capita Per Year',
 'Goat and Lamb KG Per Capita Per Year',
 'Other Meat KG Per Capita Per Year',
 'Total KG Per Capita Per Year']

# Building the Dataframe table

In [62]:
data = []

for row in rows[1:]: #1: to skip the header (make sure you put the : after and not before the num)
    cells = row.find_all(["th", "td"])
    row_values = [cell.get_text(strip=True) for cell in cells]
    data.append(row_values)

In [63]:
len(data)

45

In [64]:
data

[['Albania', '8.51', '15.19', '6.31', '22.56', '8.87', '0.27', '61.71'],
 ['Armenia', '5.15', '25.76', '11.36', '18.45', '3.88', '0.04', '64.64'],
 ['Austria', '14.43', '14.48', '42.82', '19.14', '1', '0.52', '92.39'],
 ['Azerbaijan', '2.13', '15.03', '0.81', '16.06', '8.6', '0', '42.63'],
 ['Belarus', '11.91', '22.63', '36.42', '35.13', '0.09', '0.19', '106.37'],
 ['Belgium', '24.04', '12.93', '32.3', '16.25', '0.92', '2.08', '88.52'],
 ['Bosnia and Herzegovina',
  '5.77',
  '13.27',
  '13.06',
  '21.82',
  '0.37',
  '0.4',
  '54.69'],
 ['Bulgaria', '7.32', '3.61', '34.2', '20.87', '1.41', '0.75', '68.16'],
 ['Croatia', '20.34', '14.46', '57.39', '19.54', '1.73', '1.05', '114.51'],
 ['Cyprus', '19.3', '8.2', '34.4', '29.09', '4.14', '0.5', '95.63'],
 ['Czech Republic',
  '10.68',
  '10.78',
  '47.28',
  '23.87',
  '0.29',
  '0.83',
  '93.73'],
 ['Denmark', '22.81', '21.93', '25.74', '17.83', '0.72', '0.81', '89.84'],
 ['Estonia', '13.1', '8.81', '38.06', '21.26', '0.4', '0.39', '82.02'],
 ['Finland', '31.84', '17.34', '29.36', '23.67', '0.45', '0.8', '103.46'],
 ['France', '33.56', '23.22', '33.73', '24.6', '2.44', '0.61', '118.16'],
 ['Georgia', '10.51', '7.28', '12.3', '19.19', '1.34', '0.12', '50.74'],
 ['Germany', '13.16', '14.05', '38.96', '16.51', '0.75', '1.04', '84.47'],
 ['Greece', '19.36', '14.8', '27.39', '26.23', '8.56', '1.94', '98.28'],
 ['Hungary', '6.17', '5.4', '47.08', '23.69', '0.11', '0.36', '82.81'],
 ['Iceland', '87.1', '16', '20.68', '30.74', '14.89', '11.12', '180.53'],
 ['Ireland', '19.93', '23.63', '29.11', '31.18', '4.22', '2.53', '110.6'],
 ['Italy', '29.62', '16.22', '34.96', '20.31', '0.86', '1.22', '103.19'],
 ['Kazakhstan', '3.64', '24.83', '8.01', '21.82', '8.51', '7.02', '73.83'],
 ['Latvia', '24.91', '5.68', '48.07', '29.29', '0.36', '0.26', '108.57'],
 ['Lithuania', '29.59', '5.05', '48.86', '26.55', '0.38', '0.55', '110.98'],
 ['Luxembourg', '31.11', '30.73', '33.17', '19.84', '1.09', '1.24', '117.18'],
 ['Malta', '30.37', '17.72', '22.19', '24.01', '0.83', '0.65', '95.77'],
 ['Moldova', '16.18', '1.12', '12.5', '24.93', '0.01', '0.28', '55.02'],
 ['Montenegro', '12.04', '14.01', '53.47', '19.22', '1.68', '0.05', '100.47'],
 ['Netherlands', '19.66', '16.73', '31.09', '13.78', '0.97', '2.51', '84.74'],
 ['North Macedonia', '7.01', '8.65', '14.48', '18.01', '0.8', '0.37', '49.32'],
 ['Norway', '49.87', '18.7', '25.79', '21.51', '4.52', '1.72', '122.11'],
 ['Poland', '10.84', '0.25', '51.65', '29.53', '0.03', '0.15', '92.45'],
 ['Portugal', '54.33', '22.44', '40.24', '32.82', '2.29', '0.63', '152.75'],
 ['Romania', '7.95', '4.56', '38.48', '21.59', '3.09', '0.17', '75.84'],
 ['Russia', '22.91', '12.51', '29.51', '34.23', '1.45', '4.01', '104.62'],
 ['Serbia', '7.93', '9.82', '49.11', '11.46', '4.22', '0.03', '82.57'],
 ['Slovakia', '9.85', '6.79', '40.11', '12.38', '0.11', '1.22', '70.46'],
 ['Slovenia', '12.95', '12.2', '21.18', '25.91', '0.79', '0.35', '73.38'],
 ['Spain', '40.05', '12.92', '56.5', '32.1', '1.87', '1.36', '144.8'],
 ['Sweden', '30.63', '22', '28.2', '16.35', '1.31', '0.21', '98.7'],
 ['Switzerland', '16.71', '18.68', '27.7', '18.01', '1.27', '1.02', '83.39'],
 ['Turkey', '5.44', '18.56', '0', '21.16', '7.04', '0.02', '52.22'],
 ['Ukraine', '16.02', '6.2', '18.25', '22.87', '0.27', '0.37', '63.98'],
 ['United Kingdom', '18.01', '17.3', '26.17', '35.5', '4.1', '1.01', '102.09']]

In [65]:
df = pd.DataFrame(data, columns=columns)
df.head()

,Country,Fish And Seafood KG Per Capita Per Year,Beef KG Per Capita Per Year,Pork KG Per Capita Per Year,Chicken KG Per Capita Per Year,Goat and Lamb KG Per Capita Per Year,Other Meat KG Per Capita Per Year,Total KG Per Capita Per Year
0,Albania,8.51,15.19,6.31,22.56,8.87,0.27,61.71
1,Armenia,5.15,25.76,11.36,18.45,3.88,0.04,64.64
2,Austria,14.43,14.48,42.82,19.14,1,0.52,92.39
3,Azerbaijan,2.13,15.03,0.81,16.06,8.6,0,42.63
4,Belarus,11.91,22.63,36.42,35.13,0.09,0.19,106.37

In [66]:
df

,Country,Fish And Seafood KG Per Capita Per Year,Beef KG Per Capita Per Year,Pork KG Per Capita Per Year,Chicken KG Per Capita Per Year,Goat and Lamb KG Per Capita Per Year,Other Meat KG Per Capita Per Year,Total KG Per Capita Per Year
0,Albania,8.51,15.19,6.31,22.56,8.87,0.27,61.71
1,Armenia,5.15,25.76,11.36,18.45,3.88,0.04,64.64
2,Austria,14.43,14.48,42.82,19.14,1,0.52,92.39
3,Azerbaijan,2.13,15.03,0.81,16.06,8.6,0,42.63
4,Belarus,11.91,22.63,36.42,35.13,0.09,0.19,106.37
5,Belgium,24.04,12.93,32.3,16.25,0.92,2.08,88.52
6,Bosnia and Herzegovina,5.77,13.27,13.06,21.82,0.37,0.4,54.69
7,Bulgaria,7.32,3.61,34.2,20.87,1.41,0.75,68.16
8,Croatia,20.34,14.46,57.39,19.54,1.73,1.05,114.51
9,Cyprus,19.3,8.2,34.4,29.09,4.14,0.5,95.63
10,Czech Republic,10.68,10.78,47.28,23.87,0.29,0.83,93.73
11,Denmark,22.81,21.93,25.74,17.83,0.72,0.81,89.84
12,Estonia,13.1,8.81,38.06,21.26,0.4,0.39,82.02
13,Finland,31.84,17.34,29.36,23.67,0.45,0.8,103.46
14,France,33.56,23.22,33.73,24.6,2.44,0.61,118.16
15,Georgia,10.51,7.28,12.3,19.19,1.34,0.12,50.74
16,Germany,13.16,14.05,38.96,16.51,0.75,1.04,84.47
17,Greece,19.36,14.8,27.39,26.23,8.56,1.94,98.28
18,Hungary,6.17,5.4,47.08,23.69,0.11,0.36,82.81
19,Iceland,87.1,16,20.68,30.74,14.89,11.12,180.53
20,Ireland,19.93,23.63,29.11,31.18,4.22,2.53,110.6
21,Italy,29.62,16.22,34.96,20.31,0.86,1.22,103.19
22,Kazakhstan,3.64,24.83,8.01,21.82,8.51,7.02,73.83
23,Latvia,24.91,5.68,48.07,29.29,0.36,0.26,108.57
24,Lithuania,29.59,5.05,48.86,26.55,0.38,0.55,110.98
25,Luxembourg,31.11,30.73,33.17,19.84,1.09,1.24,117.18
26,Malta,30.37,17.72,22.19,24.01,0.83,0.65,95.77
27,Moldova,16.18,1.12,12.5,24.93,0.01,0.28,55.02
28,Montenegro,12.04,14.01,53.47,19.22,1.68,0.05,100.47
29,Netherlands,19.66,16.73,31.09,13.78,0.97,2.51,84.74
30,North Macedonia,7.01,8.65,14.48,18.01,0.8,0.37,49.32
31,Norway,49.87,18.7,25.79,21.51,4.52,1.72,122.11
32,Poland,10.84,0.25,51.65,29.53,0.03,0.15,92.45
33,Portugal,54.33,22.44,40.24,32.82,2.29,0.63,152.75
34,Romania,7.95,4.56,38.48,21.59,3.09,0.17,75.84
35,Russia,22.91,12.51,29.51,34.23,1.45,4.01,104.62
36,Serbia,7.93,9.82,49.11,11.46,4.22,0.03,82.57
37,Slovakia,9.85,6.79,40.11,12.38,0.11,1.22,70.46
38,Slovenia,12.95,12.2,21.18,25.91,0.79,0.35,73.38
39,Spain,40.05,12.92,56.5,32.1,1.87,1.36,144.8
40,Sweden,30.63,22,28.2,16.35,1.31,0.21,98.7
41,Switzerland,16.71,18.68,27.7,18.01,1.27,1.02,83.39
42,Turkey,5.44,18.56,0,21.16,7.04,0.02,52.22
43,Ukraine,16.02,6.2,18.25,22.87,0.27,0.37,63.98
44,United Kingdom,18.01,17.3,26.17,35.5,4.1,1.01,102.09

# Cleaning a bit

In [67]:
#renamimng header 
# discuss with team -> must not forget that data is kg per capita per year
df.columns = ["country", "fish_seafood", "beef", "pork", "chicken",
              "goat_lamb", "other", "total"]
df.head()

      country fish_seafood   beef   pork chicken goat_lamb other   total
0     Albania         8.51  15.19   6.31   22.56      8.87  0.27   61.71
1     Armenia         5.15  25.76  11.36   18.45      3.88  0.04   64.64
2     Austria        14.43  14.48  42.82   19.14         1  0.52   92.39
3  Azerbaijan         2.13  15.03   0.81   16.06       8.6     0   42.63
4     Belarus        11.91  22.63  36.42   35.13      0.09  0.19  106.37

In [68]:
#converting nums into nums

num_cols = df.columns[1:]
df[num_cols] = df[num_cols].apply(pd.to_numeric)
df.dtypes

country             str
fish_seafood    float64
beef            float64
pork            float64
chicken         float64
goat_lamb       float64
other           float64
total           float64
dtype: object

In [69]:
#Confirming na and duplicates are 0
df.isna().sum()

country         0
fish_seafood    0
beef            0
pork            0
chicken         0
goat_lamb       0
other           0
total           0
dtype: int64

In [70]:
df["country"].duplicated().sum()

np.int64(0)

In [71]:
#Checking numbers
df["country"].str.len().describe()

count    45.00
mean      8.04
std       3.15
min       5.00
25%       6.00
50%       7.00
75%       8.00
max      22.00
Name: country, dtype: float64

In [72]:
df["country"] != df["country"].str.strip().sum()

0     True
1     True
2     True
3     True
4     True
5     True
6     True
7     True
8     True
9     True
10    True
11    True
12    True
13    True
14    True
15    True
16    True
17    True
18    True
19    True
20    True
21    True
22    True
23    True
24    True
25    True
26    True
27    True
28    True
29    True
30    True
31    True
32    True
33    True
34    True
35    True
36    True
37    True
38    True
39    True
40    True
41    True
42    True
43    True
44    True
Name: country, dtype: bool

In [73]:
df.describe()

       fish_seafood   beef   pork  chicken  goat_lamb  other   total
count         45.00  45.00  45.00    45.00      45.00  45.00   45.00
mean          19.88  14.05  30.63    22.91       2.51   1.17   91.16
std           15.64   7.01  14.72     6.02       3.16   1.95   27.84
min            2.13   0.25   0.00    11.46       0.01   0.00   42.63
25%            9.85   8.65  21.18    19.14       0.45   0.27   73.38
50%           16.18  14.46  31.09    21.82       1.27   0.61   92.39
75%           24.91  18.56  40.11    26.23       3.88   1.22  104.62
max           87.10  30.73  57.39    35.50      14.89  11.12  180.53

In [74]:
df.describe().round(2)

       fish_seafood   beef   pork  chicken  goat_lamb  other   total
count         45.00  45.00  45.00    45.00      45.00  45.00   45.00
mean          19.88  14.05  30.63    22.91       2.51   1.17   91.16
std           15.64   7.01  14.72     6.02       3.16   1.95   27.84
min            2.13   0.25   0.00    11.46       0.01   0.00   42.63
25%            9.85   8.65  21.18    19.14       0.45   0.27   73.38
50%           16.18  14.46  31.09    21.82       1.27   0.61   92.39
75%           24.91  18.56  40.11    26.23       3.88   1.22  104.62
max           87.10  30.73  57.39    35.50      14.89  11.12  180.53

In [75]:
# Rounded all nums but we can reset them to 'full precision' using this:
# pd.reset_option("display.precision")
pd.set_option("display.precision", 2)
df.describe()

       fish_seafood   beef   pork  chicken  goat_lamb  other   total
count         45.00  45.00  45.00    45.00      45.00  45.00   45.00
mean          19.88  14.05  30.63    22.91       2.51   1.17   91.16
std           15.64   7.01  14.72     6.02       3.16   1.95   27.84
min            2.13   0.25   0.00    11.46       0.01   0.00   42.63
25%            9.85   8.65  21.18    19.14       0.45   0.27   73.38
50%           16.18  14.46  31.09    21.82       1.27   0.61   92.39
75%           24.91  18.56  40.11    26.23       3.88   1.22  104.62
max           87.10  30.73  57.39    35.50      14.89  11.12  180.53