In [46]:
import pandas as pd

url = "../First Project/FAOSTAT_data_en_9-30-2026 (1).csv"

meat_consumption = pd.read_csv(url)

In [47]:
meat_consumption.head()

,Domain Code,Domain,Area Code (M49),Area,Element Code,Element,Item Code (FBS),Item,Year Code,Year,Unit,Value,Flag,Flag Description,Note
0,FBS,Food Balances (2010-),4,Afghanistan,645,Food supply quantity (kg/capita/yr),S2731,Bovine Meat,2010,2010,kg/cap,4.72,E,Estimated value,NaN
1,FBS,Food Balances (2010-),4,Afghanistan,645,Food supply quantity (kg/capita/yr),S2731,Bovine Meat,2011,2011,kg/cap,4.79,E,Estimated value,NaN
2,FBS,Food Balances (2010-),4,Afghanistan,645,Food supply quantity (kg/capita/yr),S2731,Bovine Meat,2012,2012,kg/cap,4.38,E,Estimated value,NaN
3,FBS,Food Balances (2010-),4,Afghanistan,645,Food supply quantity (kg/capita/yr),S2731,Bovine Meat,2013,2013,kg/cap,4.17,E,Estimated value,NaN
4,FBS,Food Balances (2010-),4,Afghanistan,645,Food supply quantity (kg/capita/yr),S2731,Bovine Meat,2014,2014,kg/cap,4.98,E,Estimated value,NaN

In [48]:
meat_consumption.shape

(31066, 15)

In [49]:
meat_consumption.nunique()

Domain Code            1
Domain                 1
Area Code (M49)      179
Area                 179
Element Code           1
Element                1
Item Code (FBS)       14
Item                  14
Year Code             14
Year                  14
Unit                   1
Value               3699
Flag                   1
Flag Description       1
Note                   0
dtype: int64

In [50]:
meat_consumption["Unit"].unique()

<ArrowStringArray>
['kg/cap']
Length: 1, dtype: str

In [51]:
meat_consumption["Item"].unique()

<ArrowStringArray>
[            'Bovine Meat',      'Mutton & Goat Meat',
                 'Pigmeat',            'Poultry Meat',
             'Meat, Other',         'Freshwater Fish',
           'Demersal Fish',            'Pelagic Fish',
      'Marine Fish, Other',             'Crustaceans',
             'Cephalopods',         'Molluscs, Other',
 'Aquatic Animals, Others',   'Meat, Aquatic Mammals']
Length: 14, dtype: str

In [52]:
meat_consumption = meat_consumption[["Area", "Item", "Year", "Value"]]
meat_consumption.shape

(31066, 4)

In [53]:
meat_consumption[meat_consumption["Area"].str.contains("China")]["Area"].unique()

<ArrowStringArray>
[                    'China',      'China, Hong Kong SAR',
          'China, Macao SAR',           'China, mainland',
 'China, Taiwan Province of']
Length: 5, dtype: str

In [54]:
meat_consumption = meat_consumption[meat_consumption["Area"] != "China"]

In [55]:
meat_consumption["Area"].nunique()

178

In [56]:
meat_consumption.shape

(30884, 4)

In [57]:
codes = {"Portugal": "PRT", "Spain": "ESP"}

print(codes["Portugal"])

PRT

In [58]:
from country_lookup import country_info

print(len(country_info))
print(country_info["Portugal"])
print(country_info["Portugal"][0])
print(country_info["Portugal"][1])

178
('PRT', 'Europe')
PRT
Europe

In [59]:
set(meat_consumption["Area"]) - set(country_info)

set()

In [60]:
meat_consumption.head()

          Area         Item  Year  Value
0  Afghanistan  Bovine Meat  2010   4.72
1  Afghanistan  Bovine Meat  2011   4.79
2  Afghanistan  Bovine Meat  2012   4.38
3  Afghanistan  Bovine Meat  2013   4.17
4  Afghanistan  Bovine Meat  2014   4.98

In [61]:
meat_consumption.isna().sum()

Area     0
Item     0
Year     0
Value    0
dtype: int64

In [62]:
meat_consumption["Code"] = meat_consumption["Area"].map(lambda country: country_info[country][0])

In [63]:
meat_consumption.isna().sum()

Area     0
Item     0
Year     0
Value    0
Code     0
dtype: int64

In [64]:
meat_consumption["Continent"] = meat_consumption["Area"].map(lambda country: country_info[country][1])

In [65]:
meat_consumption.head()

          Area         Item  Year  Value Code Continent
0  Afghanistan  Bovine Meat  2010   4.72  AFG      Asia
1  Afghanistan  Bovine Meat  2011   4.79  AFG      Asia
2  Afghanistan  Bovine Meat  2012   4.38  AFG      Asia
3  Afghanistan  Bovine Meat  2013   4.17  AFG      Asia
4  Afghanistan  Bovine Meat  2014   4.98  AFG      Asia

In [66]:
meat_consumption.isna().sum()

Area         0
Item         0
Year         0
Value        0
Code         0
Continent    0
dtype: int64

In [67]:
meat_consumption["Continent"].value_counts()

Continent
Asia             7792
Africa           7649
Europe           7271
North America    3904
South America    2147
Oceania          2121
Name: count, dtype: int64

In [68]:
name_fix = {
    "Bolivia (Plurinational State of)": "Bolivia",
    "China, mainland": "China",
    "China, Hong Kong SAR": "Hong Kong",
    "China, Macao SAR": "Macao",
    "China, Taiwan Province of": "Taiwan",
    "Democratic People's Republic of Korea": "North Korea",
    "Democratic Republic of the Congo": "Democratic Republic of Congo",
    "Iran (Islamic Republic of)": "Iran",
    "Lao People's Democratic Republic": "Laos",
    "Micronesia (Federated States of)": "Micronesia (country)",
    "Naoero": "Nauru",
    "Netherlands (Kingdom of the)": "Netherlands",
    "Republic of Korea": "South Korea",
    "Republic of Moldova": "Moldova",
    "Russian Federation": "Russia",
    "Syrian Arab Republic": "Syria",
    "Türkiye": "Turkey",
    "United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
    "United Republic of Tanzania": "Tanzania",
    "United States of America": "United States",
    "Venezuela (Bolivarian Republic of)": "Venezuela",
    "Viet Nam": "Vietnam",
    "Cabo Verde": "Cape Verde",
    "Timor-Leste": "East Timor",
}

In [69]:
meat_consumption["Entity"] = meat_consumption["Area"].replace(name_fix)

In [70]:
meat_consumption["Entity"].isna().sum()

np.int64(0)

In [71]:
meat_consumption[meat_consumption["Code"].isin(["IRN", "NLD", "GBR", "PRT"])][["Area", "Entity"]].drop_duplicates()

                                                    Area          Entity
13100                         Iran (Islamic Republic of)            Iran
19592                       Netherlands (Kingdom of the)     Netherlands
22479                                           Portugal        Portugal
29091  United Kingdom of Great Britain and Northern I...  United Kingdom

In [72]:
meat_consumption.head()

          Area         Item  Year  Value Code Continent       Entity
0  Afghanistan  Bovine Meat  2010   4.72  AFG      Asia  Afghanistan
1  Afghanistan  Bovine Meat  2011   4.79  AFG      Asia  Afghanistan
2  Afghanistan  Bovine Meat  2012   4.38  AFG      Asia  Afghanistan
3  Afghanistan  Bovine Meat  2013   4.17  AFG      Asia  Afghanistan
4  Afghanistan  Bovine Meat  2014   4.98  AFG      Asia  Afghanistan

In [73]:
item_map = {
    "Poultry Meat": "Poultry",
    "Bovine Meat": "Beef and buffalo",
    "Mutton & Goat Meat": "Sheep and goat",
    "Pigmeat": "Pork",
    "Meat, Other": "Other meats",
    "Freshwater Fish": "Fish and seafood",
    "Demersal Fish": "Fish and seafood",
    "Pelagic Fish": "Fish and seafood",
    "Marine Fish, Other": "Fish and seafood",
    "Crustaceans": "Fish and seafood",
    "Cephalopods": "Fish and seafood",
    "Molluscs, Other": "Fish and seafood",
    "Aquatic Animals, Others": "Fish and seafood",
    "Meat, Aquatic Mammals": "Fish and seafood",
}

In [74]:
set(meat_consumption["Item"]) - set(item_map)

set()

In [75]:
meat_consumption["Category"] = meat_consumption["Item"].map(item_map)

In [76]:
meat_consumption["Category"].isna().sum()

np.int64(0)

In [77]:
meat_consumption["Category"].value_counts()

Category
Fish and seafood    18868
Beef and buffalo     2411
Sheep and goat       2411
Poultry              2411
Other meats          2408
Pork                 2375
Name: count, dtype: int64

In [78]:
meat_grouped = meat_consumption.groupby(["Entity", "Code", "Continent", "Year", "Category"], as_index=False)["Value"].sum()
meat_grouped.shape   # expected (14427, 6)

(14427, 6)

In [79]:
meat_grouped[(meat_grouped["Code"] == "ESP") & (meat_grouped["Year"] == 2023)]

      Entity Code Continent  Year          Category  Value
12186  Spain  ESP    Europe  2023  Beef and buffalo  11.77
12187  Spain  ESP    Europe  2023  Fish and seafood  36.80
12188  Spain  ESP    Europe  2023       Other meats   1.44
12189  Spain  ESP    Europe  2023              Pork  53.04
12190  Spain  ESP    Europe  2023           Poultry  32.96
12191  Spain  ESP    Europe  2023    Sheep and goat   1.59

In [80]:
meat_cols = ["Poultry", "Beef and buffalo", "Sheep and goat", "Pork", "Other meats", "Fish and seafood"]

wide = meat_grouped.pivot(index=["Entity", "Code", "Continent", "Year"], columns="Category", values="Value").reset_index()
wide.columns.name = None
wide = wide[["Entity", "Code", "Continent", "Year"] + meat_cols]
wide.shape

(2411, 10)

In [81]:
wide[meat_cols].isna().sum()

Poultry              0
Beef and buffalo     0
Sheep and goat       0
Pork                36
Other meats          3
Fish and seafood     0
dtype: int64

In [82]:
wide[meat_cols] = wide[meat_cols].fillna(0).round(2)
wide[meat_cols].isna().sum()   # all 0 now

Poultry             0
Beef and buffalo    0
Sheep and goat      0
Pork                0
Other meats         0
Fish and seafood    0
dtype: int64

In [83]:
wide["Complete_series"] = wide.groupby("Code")["Year"].transform("nunique") == wide["Year"].nunique()
wide.groupby("Code")["Complete_series"].first().value_counts()   # True 168, False 10

Complete_series
True     168
False     10
Name: count, dtype: int64

## Dataset 1: continents

In [84]:
continent_codes = {"Africa": "OWID_AFR", "Asia": "OWID_ASI", "Europe": "OWID_EUR",
                   "North America": "OWID_NAM", "Oceania": "OWID_OCE", "South America": "OWID_SAM"}

complete = wide[wide["Complete_series"]]
meat_continents = complete.groupby(["Continent", "Year"])[meat_cols].mean().round(2).reset_index()
meat_continents["Code"] = meat_continents["Continent"].map(continent_codes)
meat_continents = meat_continents.rename(columns={"Continent": "Entity"})
meat_continents = meat_continents[["Entity", "Code", "Year"] + meat_cols]
meat_continents.shape

(84, 9)

In [85]:
meat_continents[meat_continents["Year"] == 2023]

,Entity,Code,Year,Poultry,Beef and buffalo,Sheep and goat,Pork,Other meats,Fish and seafood
13,Africa,OWID_AFR,2023,11.71,6.13,2.30,3.08,2.03,12.35
27,Asia,OWID_ASI,2023,19.32,10.61,5.51,8.96,1.67,20.64
41,Europe,OWID_EUR,2023,25.34,13.60,2.08,34.31,1.18,21.45
55,North America,OWID_NAM,2023,46.40,11.80,1.18,14.63,0.28,20.20
69,Oceania,OWID_OCE,2023,34.66,12.25,4.63,15.42,4.72,33.63
83,South America,OWID_SAM,2023,37.81,18.17,0.77,13.32,0.61,11.83

## Dataset 2: the 9 countries

In [86]:
wanted = ["IRN", "NLD", "UKR", "FRA", "ESP", "ITA", "ARG", "GBR", "PRT", "BRA"]

meat_countries = wide[wide["Code"].isin(wanted)].drop(columns=["Continent", "Complete_series"])
meat_countries = meat_countries.sort_values(["Entity", "Year"]).reset_index(drop=True)
print(meat_countries.shape)                 
print(set(wanted) - set(meat_countries["Code"]))

(140, 9)
set()

In [93]:
meat_columns = ["Poultry", "Beef and buffalo", "Sheep and goat", "Pork", "Other meats", "Fish and seafood"]

meat_countries["Total"] = meat_countries[meat_columns].sum(axis=1)

total = (
    meat_countries[
        (meat_countries["Code"].isin(wanted)) &
        (meat_countries["Year"] == 2023)
    ][["Code"] + meat_columns + ["Total"]]
    .copy()
)

total = total.sort_values("Total", ascending=False)

meat_countries[meat_countries["Year"] == 2023].sort_values("Total", ascending=False)

,Entity,Code,Year,Poultry,Beef and buffalo,Sheep and goat,Pork,Other meats,Fish and seafood,Total
97,Portugal,PRT,2023,34.94,22.43,2.01,39.29,0.65,53.50,152.82
111,Spain,ESP,2023,32.96,11.77,1.59,53.04,1.44,36.80,137.60
13,Argentina,ARG,2023,46.73,48.99,1.07,17.04,1.12,7.12,122.07
41,France,FRA,2023,24.74,21.65,2.21,31.18,0.52,32.64,112.94
27,Brazil,BRA,2023,47.55,39.07,0.72,16.75,0.48,8.19,112.76
139,United Kingdom,GBR,2023,38.18,16.85,3.66,24.66,1.09,17.69,102.13
69,Italy,ITA,2023,20.47,14.49,0.87,34.13,1.24,29.39,100.59
83,Netherlands,NLD,2023,14.76,16.88,0.84,36.70,2.39,19.09,90.66
125,Ukraine,UKR,2023,25.17,6.08,0.31,17.49,0.40,16.86,66.31
55,Iran,IRN,2023,23.47,3.23,3.10,0.00,0.10,11.30,41.20

In [94]:
meat_columns = ["Poultry", "Beef and buffalo", "Sheep and goat", "Pork", "Other meats"]

meat_countries["Total"] = meat_countries[meat_columns].sum(axis=1)

total = (
    meat_countries[
        (meat_countries["Code"].isin(wanted)) &
        (meat_countries["Year"] == 2023)
    ][["Code"] + meat_columns + ["Total"]]
    .copy()
)

total = total.sort_values("Total", ascending=False)

meat_countries[meat_countries["Year"] == 2023].sort_values("Total", ascending=False)

,Entity,Code,Year,Poultry,Beef and buffalo,Sheep and goat,Pork,Other meats,Fish and seafood,Total
13,Argentina,ARG,2023,46.73,48.99,1.07,17.04,1.12,7.12,114.95
27,Brazil,BRA,2023,47.55,39.07,0.72,16.75,0.48,8.19,104.57
111,Spain,ESP,2023,32.96,11.77,1.59,53.04,1.44,36.80,100.80
97,Portugal,PRT,2023,34.94,22.43,2.01,39.29,0.65,53.50,99.32
139,United Kingdom,GBR,2023,38.18,16.85,3.66,24.66,1.09,17.69,84.44
41,France,FRA,2023,24.74,21.65,2.21,31.18,0.52,32.64,80.30
83,Netherlands,NLD,2023,14.76,16.88,0.84,36.70,2.39,19.09,71.57
69,Italy,ITA,2023,20.47,14.49,0.87,34.13,1.24,29.39,71.20
125,Ukraine,UKR,2023,25.17,6.08,0.31,17.49,0.40,16.86,49.45
55,Iran,IRN,2023,23.47,3.23,3.10,0.00,0.10,11.30,29.90

##  Final checks and option save
Both tables must have the plan's columns, no empty values, and the right number of rows.
discovered that if the last two lines run we can create CSV file that will appear in our file to use

In [88]:
print(meat_continents.shape, meat_continents.isna().sum().sum(), meat_continents["Code"].unique())
print(meat_countries.shape, meat_countries.isna().sum().sum(), meat_countries["Code"].nunique())

#meat_continents.to_csv("meat_continents_clean.csv", index=False)
meat_countries.to_csv("meat_countries_clean.csv", index=False)

(84, 9) 0 <ArrowStringArray>
['OWID_AFR', 'OWID_ASI', 'OWID_EUR', 'OWID_NAM', 'OWID_OCE', 'OWID_SAM']
Length: 6, dtype: str
(140, 9) 0 10